import assert from "node:assert/strict";
import test from "node:test";
import { DesignProgram, buildTopology, evaluateDimensions, spatialAnalysis, resolveReference, exportDxf, KERNEL_CAPABILITIES } from "../kernel/src/native-index.js";

function square(){const p=new DesignProgram();p.addGeometry("a",()=>({kind:"line",start:{x:0,y:0},end:{x:10,y:0}}));p.addGeometry("b",()=>({kind:"line",start:{x:10,y:0},end:{x:10,y:10}}));p.addGeometry("c",()=>({kind:"line",start:{x:10,y:10},end:{x:0,y:10}}));p.addGeometry("d",()=>({kind:"line",start:{x:0,y:10},end:{x:0,y:0}}));return p.snapshot()}
test("native topology derives a closed wire",()=>{const t=buildTopology(square());assert.equal(t.wires.length,1);assert.equal(t.wires[0]!.closed,true);assert.equal(t.wires[0]!.directions.length,4)});
test("native dimensions evaluate semantic line length",()=>{const s=square();assert.equal(evaluateDimensions(s,[{id:"d",kind:"length",firstGeometryId:"a"}])[0]!.value,10)});
test("native dimensions use circumference and arc length, not chord length",()=>{const p=new DesignProgram();p.addGeometry("circle",()=>({kind:"circle",center:{x:0,y:0},radius:2}));p.addGeometry("quarter",()=>({kind:"arc",center:{x:0,y:0},radius:2,startAngle:0,endAngle:Math.PI/2}));const s=p.snapshot();const dims=evaluateDimensions(s,[{id:"c",kind:"length",firstGeometryId:"circle"},{id:"a",kind:"length",firstGeometryId:"quarter"}]);assert.ok(Math.abs(dims[0]!.value-4*Math.PI)<1e-12);assert.ok(Math.abs(dims[1]!.value-Math.PI)<1e-12)});
test("native spatial analysis uses exact narrow phase after AABB broad phase",()=>{const a={id:"a",geometry:{kind:"line" as const,start:{x:0,y:0},end:{x:10,y:10}}};const b={id:"b",geometry:{kind:"line" as const,start:{x:0,y:5},end:{x:10,y:15}}};const r=spatialAnalysis([a,b])[0]!;assert.equal(r.intersects,false);assert.ok(r.distance>0);assert.equal(r.method,"exact-2d")});
test("native circles are closed topology edges without fabricated endpoints",()=>{const p=new DesignProgram();p.addGeometry("c",()=>({kind:"circle",center:{x:0,y:0},radius:5}));const t=buildTopology(p.snapshot());assert.equal(t.edges[0]!.closed,true);assert.equal(t.edges[0]!.startVertexId,null);assert.equal(t.edges[0]!.endVertexId,null);assert.equal(t.wires[0]!.closed,true)});
test("native topology rejects branch ambiguity instead of choosing arbitrarily",()=>{const p=new DesignProgram();p.addGeometry("a",()=>({kind:"line",start:{x:0,y:0},end:{x:1,y:0}}));p.addGeometry("b",()=>({kind:"line",start:{x:0,y:0},end:{x:0,y:1}}));p.addGeometry("c",()=>({kind:"line",start:{x:0,y:0},end:{x:-1,y:0}}));assert.throws(()=>buildTopology(p.snapshot()),/Non-manifold topology/)});
test("native invalid constraint domains fail closed",()=>{const p=new DesignProgram();p.addGeometry("c",()=>({kind:"circle",center:{x:0,y:0},radius:1}));p.horizontal({kind:"geometry",entityId:"c"});assert.throws(()=>p.snapshot(),/horizontal requires a line/)});
test("native reference migration is explicit",()=>{assert.equal(resolveReference({kind:"geometry",id:"old"},{old:"new"})[0]!.id,"new")});
test("native DXF export is deterministic",()=>{const s=square();const a=exportDxf(s),b=exportDxf(s);assert.equal(a,b);assert.match(a,/SECTION/);assert.match(a,/LINE/)});
test("native capability list is immutable and transport-neutral",()=>{assert.ok(KERNEL_CAPABILITIES.some(c=>c.id==="constraints.solve"));assert.equal(Object.isFrozen(KERNEL_CAPABILITIES),true)});
