import assert from "node:assert/strict";
import test from "node:test";
import { DesignProgram, analyzeConstraints, solveConstraints } from "../kernel/api/src/native-index.js";

test("native solver analyzes a satisfied horizontal constraint",()=>{const p=new DesignProgram();p.addGeometry("edge",()=>({kind:"line",start:{x:0,y:0},end:{x:10,y:0}}));p.horizontal({kind:"geometry",entityId:"edge"});const result=analyzeConstraints(p.snapshot());assert.equal(result.satisfied,true);assert.equal(result.maxResidual,0);assert.equal(result.valid,true);assert.equal(result.degreesOfFreedom,3);assert.equal(result.rank,1)});
test("native solver satisfies distance constraint",()=>{const p=new DesignProgram();p.addGeometry("edge",()=>({kind:"line",start:{x:0,y:0},end:{x:7,y:0}}));p.distance("edge",10);const solved=solveConstraints(p.snapshot(),{maxIterations:50});assert.equal(solved.converged,true);assert.equal(solved.analysis.valid,true);assert.ok(Number.isFinite(solved.analysis.conditionEstimate));assert.equal(solved.analysis.degreesOfFreedom,3);const line=solved.geometry.find(item=>item.id==="edge")!.geometry;assert.equal(line.kind,"line");assert.ok(Math.abs(Math.hypot(line.end.x-line.start.x,line.end.y-line.start.y)-10)<1e-7)});
test("native solver uses scaled least-squares semantics for mixed geometry magnitudes without falsely requiring full rank",()=>{const p=new DesignProgram();p.addGeometry("large",()=>({kind:"line",start:{x:1e6,y:0},end:{x:1e6+1000,y:0}}));p.addGeometry("small",()=>({kind:"line",start:{x:0,y:0},end:{x:0.001,y:0}}));p.horizontal({kind:"geometry",entityId:"large"});p.horizontal({kind:"geometry",entityId:"small"});const analysis=analyzeConstraints(p.snapshot());assert.equal(analysis.valid,true);assert.equal(analysis.satisfied,true);assert.equal(analysis.rank,2);assert.equal(analysis.degreesOfFreedom,6);assert.ok(Number.isFinite(analysis.conditionEstimate));assert.equal(analysis.wellConditioned,true)});
test("native solver reports finite conditioning for a fully constrained, well-scaled system",()=>{const p=new DesignProgram();p.addGeometry("edge",()=>({kind:"line",start:{x:1e6,y:2e6},end:{x:1e6+1000,y:2e6} }));p.fixed("edge");const analysis=analyzeConstraints(p.snapshot());assert.equal(analysis.valid,true);assert.equal(analysis.satisfied,true);assert.equal(analysis.degreesOfFreedom,0);assert.ok(Number.isFinite(analysis.conditionEstimate));assert.equal(analysis.wellConditioned,true)});
test("native solver rejects invalid constraint domains fail closed",()=>{const p=new DesignProgram();p.addGeometry("circle",()=>({kind:"circle",center:{x:0,y:0},radius:1}));const snapshot={...p.snapshot(),constraints:[{id:"bad",constraint:{kind:"horizontal" as const,entityId:"circle"}}]};const solved=solveConstraints(snapshot);assert.equal(solved.converged,false);assert.equal(solved.reason,"invalid-domain");assert.equal(solved.analysis.valid,false)});
test("native solver preserves immutable input snapshot",()=>{const p=new DesignProgram();p.addGeometry("edge",()=>({kind:"line",start:{x:0,y:0},end:{x:5,y:0}}));p.distance("edge",10);const original=p.snapshot();const solved=solveConstraints(original);assert.notDeepEqual(solved.geometry[0]?.geometry,original.geometry[0]?.geometry);assert.deepEqual(original.geometry[0]?.geometry,{kind:"line",start:{x:0,y:0},end:{x:5,y:0}})});
