//! Exact value-preserving operations on tensor-product NURBS surfaces.
//!
//! U/V knot insertion and parametric reversal operate in homogeneous space and
//! preserve the represented rational surface. Control-net ordering remains
//! U-major then V-major, matching `NurbsSurface2D`.

use super::nurbs_surface::{NurbsSurface2D,NurbsSurfaceError,Point3};

#[derive(Clone,Copy)]struct H{x:f64,y:f64,z:f64,w:f64}
fn hom(p:Point3,w:f64)->H{H{x:p.x*w,y:p.y*w,z:p.z*w,w}}
fn point(h:H)->Result<(Point3,f64),NurbsSurfaceError>{if h.w<=0.{return Err(NurbsSurfaceError::ZeroProjectiveWeight);}let p=Point3{x:h.x/h.w,y:h.y/h.w,z:h.z/h.w};if p.x.is_finite()&&p.y.is_finite()&&p.z.is_finite(){Ok((p,h.w))}else{Err(NurbsSurfaceError::Overflow)}}
fn lerp(a:H,b:H,t:f64)->H{H{x:a.x*(1.-t)+b.x*t,y:a.y*(1.-t)+b.y*t,z:a.z*(1.-t)+b.z*t,w:a.w*(1.-t)+b.w*t}}
fn span(u:f64,p:usize,k:&[f64],ncp:usize)->usize{let n=ncp-1;if u>=k[n+1]{n}else if u<=k[p]{p}else{let mut lo=p;let mut hi=n+1;let mut m=(lo+hi)/2;while u<k[m]||u>=k[m+1]{if u<k[m]{hi=m}else{lo=m};m=(lo+hi)/2;}m}}
fn insert_vector(points:&[H],knots:&[f64],degree:usize,u:f64)->Result<(Vec<H>,Vec<f64>),NurbsSurfaceError>{let n=points.len()-1;let s=knots.iter().filter(|x|**x==u).count();if s>=degree{return Err(NurbsSurfaceError::InvalidKnotCount);}let k=span(u,degree,knots,points.len());let mut q=vec![H{x:0.,y:0.,z:0.,w:0.};points.len()+1];for i in 0..=k-degree{q[i]=points[i];}for i in (k-s)..=n{q[i+1]=points[i];}if k>=degree+1{for i in (k-degree+1)..=k-s{let den=knots[i+degree]-knots[i];if den==0.{return Err(NurbsSurfaceError::InvalidDomain);}q[i]=lerp(points[i-1],points[i],(u-knots[i])/den);}}let mut uq=Vec::with_capacity(knots.len()+1);for i in 0..=k{uq.push(knots[i]);}uq.push(u);for i in k+1..knots.len(){uq.push(knots[i]);}Ok((q,uq))}

pub fn insert_knot_u(surface:&NurbsSurface2D,u:f64)->Result<NurbsSurface2D,NurbsSurfaceError>{surface.validate()?;if!u.is_finite(){return Err(NurbsSurfaceError::NonFinite);}let(umin,umax,_,_)=surface.parameter_domain()?;if u<=umin||u>=umax{return Err(NurbsSurfaceError::OutOfDomain);}let nu=surface.knots_u.len()-surface.degree_u-1;let nv=surface.knots_v.len()-surface.degree_v-1;let mut columns=Vec::with_capacity(nv);for j in 0..nv{let mut col=Vec::with_capacity(nu);for i in 0..nu{let k=i*nv+j;col.push(hom(surface.control_points[k],surface.weights[k]));}columns.push(insert_vector(&col,&surface.knots_u,surface.degree_u,u)?.0);}let (_,ku)=insert_vector(&(0..nu).map(|_|hom(Point3{x:0.,y:0.,z:0.},1.)).collect::<Vec<_>>(),&surface.knots_u,surface.degree_u,u)?;let new_nu=nu+1;let mut cp=Vec::with_capacity(new_nu*nv);let mut wt=Vec::with_capacity(new_nu*nv);for i in 0..new_nu{for j in 0..nv{let(p,w)=point(columns[j][i])?;cp.push(p);wt.push(w);}}let result=NurbsSurface2D::new(surface.degree_u,surface.degree_v,cp,wt,ku,surface.knots_v.clone());result.validate()?;Ok(result)}

pub fn insert_knot_v(surface:&NurbsSurface2D,v:f64)->Result<NurbsSurface2D,NurbsSurfaceError>{surface.validate()?;if!v.is_finite(){return Err(NurbsSurfaceError::NonFinite);}let(_,_,vmin,vmax)=surface.parameter_domain()?;if v<=vmin||v>=vmax{return Err(NurbsSurfaceError::OutOfDomain);}let nu=surface.knots_u.len()-surface.degree_u-1;let nv=surface.knots_v.len()-surface.degree_v-1;let mut rows=Vec::with_capacity(nu);for i in 0..nu{let mut row=Vec::with_capacity(nv);for j in 0..nv{let k=i*nv+j;row.push(hom(surface.control_points[k],surface.weights[k]));}rows.push(insert_vector(&row,&surface.knots_v,surface.degree_v,v)?.0);}let (_,kv)=insert_vector(&(0..nv).map(|_|hom(Point3{x:0.,y:0.,z:0.},1.)).collect::<Vec<_>>(),&surface.knots_v,surface.degree_v,v)?;let new_nv=nv+1;let mut cp=Vec::with_capacity(nu*new_nv);let mut wt=Vec::with_capacity(nu*new_nv);for i in 0..nu{for j in 0..new_nv{let(p,w)=point(rows[i][j])?;cp.push(p);wt.push(w);}}let result=NurbsSurface2D::new(surface.degree_u,surface.degree_v,cp,wt,surface.knots_u.clone(),kv);result.validate()?;Ok(result)}

pub fn reverse_u(surface:&NurbsSurface2D)->Result<NurbsSurface2D,NurbsSurfaceError>{surface.validate()?;let(nu,nv)=(surface.knots_u.len()-surface.degree_u-1,surface.knots_v.len()-surface.degree_v-1);let(a,b,_,_)=surface.parameter_domain()?;let mut cp=Vec::with_capacity(surface.control_points.len());let mut wt=Vec::with_capacity(surface.weights.len());for i in (0..nu).rev(){for j in 0..nv{let k=i*nv+j;cp.push(surface.control_points[k]);wt.push(surface.weights[k]);}}let ku=surface.knots_u.iter().rev().map(|u|a+b-*u).collect();let result=NurbsSurface2D::new(surface.degree_u,surface.degree_v,cp,wt,ku,surface.knots_v.clone());result.validate()?;Ok(result)}

pub fn reverse_v(surface:&NurbsSurface2D)->Result<NurbsSurface2D,NurbsSurfaceError>{surface.validate()?;let(nu,nv)=(surface.knots_u.len()-surface.degree_u-1,surface.knots_v.len()-surface.degree_v-1);let(_,_,a,b)=surface.parameter_domain()?;let mut cp=Vec::with_capacity(surface.control_points.len());let mut wt=Vec::with_capacity(surface.weights.len());for i in 0..nu{for j in (0..nv).rev(){let k=i*nv+j;cp.push(surface.control_points[k]);wt.push(surface.weights[k]);}}let kv=surface.knots_v.iter().rev().map(|u|a+b-*u).collect();let result=NurbsSurface2D::new(surface.degree_u,surface.degree_v,cp,wt,surface.knots_u.clone(),kv);result.validate()?;Ok(result)}

#[cfg(test)]
mod tests{use super::*;fn patch()->NurbsSurface2D{NurbsSurface2D::new(2,1,vec![Point3{x:0.,y:0.,z:0.},Point3{x:0.,y:1.,z:0.},Point3{x:1.,y:0.,z:1.},Point3{x:1.,y:1.,z:1.},Point3{x:2.,y:0.,z:0.},Point3{x:2.,y:1.,z:0.},Point3{x:3.,y:0.,z:1.},Point3{x:3.,y:1.,z:1.}],vec![1.;8],vec![0.,0.,0.,1.,2.,2.,2.],vec![0.,0.,1.,1.])}#[test]fn u_insertion_preserves_surface(){let s=patch();let q=insert_knot_u(&s,.5).unwrap();for(u,v)in[(0.,0.),(.3,.5),(.9,.2),(1.5,.8),(1.9,.4),(2.,1.)]{let a=s.point_at(u,v).unwrap();let b=q.point_at(u,v).unwrap();assert!((a.x-b.x).abs()<1e-11&&(a.y-b.y).abs()<1e-11&&(a.z-b.z).abs()<1e-11);}}#[test]fn reversal_preserves_geometry(){let s=patch();let r=reverse_u(&s).unwrap();for u in[0.,.2,.5,.9,1.]{let a=s.point_at(u,.4).unwrap();let b=r.point_at(2.-u,.4).unwrap();assert!((a.x-b.x).abs()<1e-11&&(a.z-b.z).abs()<1e-11);}}}
