use umlcad_v6_geometry_api::{GeometryBackend, GeometryError, GeometryResult, ToleranceContext};

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Point3 { pub x: f64, pub y: f64, pub z: f64 }
impl Point3 {
    fn finite(self)->bool{self.x.is_finite()&&self.y.is_finite()&&self.z.is_finite()}
    fn sub(self,o:Self)->Self{Self{x:self.x-o.x,y:self.y-o.y,z:self.z-o.z}}
    fn dot(self,o:Self)->f64{self.x*o.x+self.y*o.y+self.z*o.z}
    fn cross(self,o:Self)->Self{Self{x:self.y*o.z-self.z*o.y,y:self.z*o.x-self.x*o.z,z:self.x*o.y-self.y*o.x}}
    fn norm(self)->f64{self.dot(self).sqrt()}
    fn scale(self,f:f64)->Self{Self{x:self.x*f,y:self.y*f,z:self.z*f}}
    fn normalized(self)->Result<Self,GeometryError>{let n=self.norm();if !n.is_finite()||n==0.{return Err(GeometryError::InvalidInput("sweep direction must be finite and non-zero"));}Ok(self.scale(1./n))}
}
#[derive(Clone, Copy, Debug, PartialEq)] pub struct CircularProfile{pub center:Point3,pub normal:Point3,pub radius:f64}
#[derive(Clone, Copy, Debug, PartialEq)] pub struct LinearPath{pub start:Point3,pub end:Point3}
#[derive(Clone, Copy, Debug, PartialEq)] pub struct LinearCircularSweep{pub profile:CircularProfile,pub path:LinearPath}
impl LinearCircularSweep{
 pub fn validate(self,tolerance: ToleranceContext)->Result<(),GeometryError>{tolerance.validate()?;if !self.profile.center.finite()||!self.profile.normal.finite()||!self.path.start.finite()||!self.path.end.finite()||!self.profile.radius.is_finite(){return Err(GeometryError::InvalidInput("sweep contains non-finite geometry"));}if self.profile.radius<=tolerance.modeling{return Err(GeometryError::InvalidInput("sweep profile radius must exceed modeling tolerance"));}let path=self.path.end.sub(self.path.start);if path.norm()<=tolerance.modeling{return Err(GeometryError::InvalidInput("sweep path must be non-degenerate"));}let pu=path.normalized()?;let nu=self.profile.normal.normalized()?;if (1.-nu.dot(pu).abs())>tolerance.validation{return Err(GeometryError::InvalidInput("sweep profile normal must be parallel to the linear path"));}if self.profile.center.sub(self.path.start).norm()>tolerance.validation{return Err(GeometryError::InvalidInput("sweep profile center must coincide with path start"));}Ok(())}
 pub fn length(self,tolerance: ToleranceContext)->Result<f64,GeometryError>{self.validate(tolerance)?;Ok(self.path.end.sub(self.path.start).norm())}
 pub fn volume(self,tolerance: ToleranceContext)->Result<f64,GeometryError>{let l=self.length(tolerance)?;Ok(std::f64::consts::PI*self.profile.radius*self.profile.radius*l)}
 fn alignment_to_z(self,tolerance: ToleranceContext)->Result<(Point3,f64),GeometryError>{self.validate(tolerance)?;let d=self.path.end.sub(self.path.start).normalized()?;let z=Point3{x:0.,y:0.,z:1.};let dot=d.dot(z).clamp(-1.,1.);if dot>=1.-tolerance.validation{return Ok((Point3{x:1.,y:0.,z:0.},0.));}if dot<=-1.+tolerance.validation{return Ok((Point3{x:1.,y:0.,z:0.},std::f64::consts::PI));}Ok((z.cross(d).normalized()?,dot.acos()))}
 pub fn realize_with<B:GeometryBackend>(self,backend:&B,tolerance: ToleranceContext)->Result<GeometryResult<B::Shape>,GeometryError>{self.validate(tolerance)?;let l=self.path.end.sub(self.path.start).norm();let base=backend.cylinder_solid(self.profile.radius,l,tolerance)?.shape;let(axis,angle)=self.alignment_to_z(tolerance)?;let rotated=backend.rotate(&base,axis.x,axis.y,axis.z,angle,tolerance)?.shape;backend.translate(&rotated,self.path.start.x,self.path.start.y,self.path.start.z,tolerance)}
}
#[derive(Clone, Copy, Debug, PartialEq)] pub struct TwoSegmentCircularSweep{pub profile:CircularProfile,pub corner:Point3,pub end:Point3}
impl TwoSegmentCircularSweep{
 pub fn validate(self,tolerance: ToleranceContext)->Result<(),GeometryError>{tolerance.validate()?;if !self.profile.center.finite()||!self.profile.normal.finite()||!self.corner.finite()||!self.end.finite()||!self.profile.radius.is_finite(){return Err(GeometryError::InvalidInput("two-segment sweep contains non-finite geometry"));}if self.profile.radius<=tolerance.modeling{return Err(GeometryError::InvalidInput("two-segment sweep profile radius must exceed modeling tolerance"));}let first_vec=self.corner.sub(self.profile.center);let second_vec=self.end.sub(self.corner);if first_vec.norm()<=tolerance.modeling{return Err(GeometryError::InvalidInput("two-segment sweep requires a non-degenerate first segment"));}if second_vec.norm()<=tolerance.modeling{return Err(GeometryError::InvalidInput("two-segment sweep requires a non-degenerate second segment"));}let first=first_vec.normalized()?;let second=second_vec.normalized()?;let normal=self.profile.normal.normalized()?;if (1.-normal.dot(first).abs())>tolerance.validation{return Err(GeometryError::InvalidInput("two-segment sweep profile normal must be parallel to first path segment"));}if (1.-first.dot(second).abs())<=tolerance.validation{return Err(GeometryError::InvalidInput("two-segment sweep requires a genuine path corner"));}Ok(())}
 pub fn segment_lengths(self,tolerance: ToleranceContext)->Result<(f64,f64),GeometryError>{self.validate(tolerance)?;Ok((self.corner.sub(self.profile.center).norm(),self.end.sub(self.corner).norm()))}
 pub fn total_path_length(self,tolerance: ToleranceContext)->Result<f64,GeometryError>{let(a,b)=self.segment_lengths(tolerance)?;Ok(a+b)}
 pub fn realize_with<B:GeometryBackend>(self,backend:&B,tolerance: ToleranceContext)->Result<GeometryResult<B::Shape>,GeometryError>{self.validate(tolerance)?;let first=LinearCircularSweep{profile:self.profile,path:LinearPath{start:self.profile.center,end:self.corner}};let second=LinearCircularSweep{profile:CircularProfile{center:self.corner,normal:self.end.sub(self.corner),radius:self.profile.radius},path:LinearPath{start:self.corner,end:self.end}};let a=first.realize_with(backend,tolerance)?.shape;let b=second.realize_with(backend,tolerance)?.shape;backend.fuse(&a,&b,tolerance)}
}
#[derive(Clone, Copy, Debug, PartialEq)] pub struct LinearVariableRadiusSweep{pub start:Point3,pub end:Point3,pub normal:Point3,pub start_radius:f64,pub end_radius:f64}
impl LinearVariableRadiusSweep{
 pub fn validate(self,tolerance: ToleranceContext)->Result<(),GeometryError>{tolerance.validate()?;if !self.start.finite()||!self.end.finite()||!self.normal.finite()||!self.start_radius.is_finite()||!self.end_radius.is_finite(){return Err(GeometryError::InvalidInput("variable-radius sweep contains non-finite geometry"));}if self.start_radius<=tolerance.modeling||self.end_radius<=tolerance.modeling{return Err(GeometryError::InvalidInput("variable-radius sweep radii must exceed modeling tolerance"));}let path=self.end.sub(self.start);if path.norm()<=tolerance.modeling{return Err(GeometryError::InvalidInput("variable-radius sweep path must be non-degenerate"));}let pu=path.normalized()?;let nu=self.normal.normalized()?;if (1.-nu.dot(pu).abs())>tolerance.validation{return Err(GeometryError::InvalidInput("variable-radius sweep normal must be parallel to the path"));}Ok(())}
 pub fn length(self,tolerance: ToleranceContext)->Result<f64,GeometryError>{self.validate(tolerance)?;Ok(self.end.sub(self.start).norm())}
 pub fn volume(self,tolerance: ToleranceContext)->Result<f64,GeometryError>{let l=self.length(tolerance)?;Ok(std::f64::consts::PI*l*(self.start_radius*self.start_radius+self.start_radius*self.end_radius+self.end_radius*self.end_radius)/3.)}
 fn alignment_to_z(self,tolerance: ToleranceContext)->Result<(Point3,f64),GeometryError>{self.validate(tolerance)?;let d=self.end.sub(self.start).normalized()?;let z=Point3{x:0.,y:0.,z:1.};let dot=d.dot(z).clamp(-1.,1.);if dot>=1.-tolerance.validation{return Ok((Point3{x:1.,y:0.,z:0.},0.));}if dot<=-1.+tolerance.validation{return Ok((Point3{x:1.,y:0.,z:0.},std::f64::consts::PI));}Ok((z.cross(d).normalized()?,dot.acos()))}
 pub fn realize_with<B:GeometryBackend>(self,backend:&B,tolerance: ToleranceContext)->Result<GeometryResult<B::Shape>,GeometryError>{self.validate(tolerance)?;let l=self.end.sub(self.start).norm();let base=if self.start_radius==self.end_radius{backend.cylinder_solid(self.start_radius,l,tolerance)?.shape}else{backend.cone_solid(self.start_radius,self.end_radius,l,tolerance)?.shape};let(axis,angle)=self.alignment_to_z(tolerance)?;let rotated=backend.rotate(&base,axis.x,axis.y,axis.z,angle,tolerance)?.shape;backend.translate(&rotated,self.start.x,self.start.y,self.start.z,tolerance)}
}
pub trait SweepBackend:GeometryBackend{fn sweep_linear_circular(&self,definition:LinearCircularSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>;}
pub trait TwoSegmentSweepBackend:GeometryBackend{fn sweep_two_segment_circular(&self,definition:TwoSegmentCircularSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>;}
pub trait VariableSweepBackend:GeometryBackend{fn sweep_linear_variable_radius(&self,definition:LinearVariableRadiusSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>;}
#[cfg(test)]mod tests{
 use super::*;fn tolerance()->ToleranceContext{ToleranceContext{modeling:1e-9,validation:1e-9}}
 fn sweep()->LinearCircularSweep{LinearCircularSweep{profile:CircularProfile{center:Point3{x:0.,y:0.,z:0.},normal:Point3{x:0.,y:0.,z:1.},radius:2.},path:LinearPath{start:Point3{x:0.,y:0.,z:0.},end:Point3{x:0.,y:0.,z:10.}}}}
 #[test]fn linear_circular_sweep_has_exact_length_and_volume(){let v=sweep();assert_eq!(v.length(tolerance()).unwrap(),10.);assert!((v.volume(tolerance()).unwrap()-40.*std::f64::consts::PI).abs()<1e-12);}
 #[test]fn linear_circular_sweep_accepts_antiparallel_profile_normal(){let mut v=sweep();v.profile.normal=Point3{x:0.,y:0.,z:-1.};assert!(v.validate(tolerance()).is_ok());}
 #[test]fn linear_sweep_alignment_handles_parallel_and_antiparallel_paths(){let mut v=sweep();let(a,p)=v.alignment_to_z(tolerance()).unwrap();assert_eq!(a,Point3{x:1.,y:0.,z:0.});assert_eq!(p,0.);v.path.end=Point3{x:0.,y:0.,z:-10.};v.profile.normal=Point3{x:0.,y:0.,z:-1.};let(a,p)=v.alignment_to_z(tolerance()).unwrap();assert_eq!(a,Point3{x:1.,y:0.,z:0.});assert_eq!(p,std::f64::consts::PI);}
 #[test]fn linear_sweep_alignment_is_finite_for_general_direction(){let mut v=sweep();v.path.end=Point3{x:3.,y:4.,z:12.};v.profile.normal=Point3{x:3.,y:4.,z:12.};let(a,p)=v.alignment_to_z(tolerance()).unwrap();assert!(a.finite());assert!(p.is_finite());assert!((a.norm()-1.).abs()<1e-12);}
 #[test]fn sweep_rejects_misaligned_profile_normal(){let mut v=sweep();v.profile.normal=Point3{x:1.,y:0.,z:0.};assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("sweep profile normal must be parallel to the linear path")));}
 #[test]fn sweep_rejects_misaligned_profile_center(){let mut v=sweep();v.profile.center=Point3{x:0.,y:0.,z:1e-3};assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("sweep profile center must coincide with path start")));}
 #[test]fn sweep_rejects_degenerate_path_and_radius(){let mut v=sweep();v.path.end=v.path.start;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("sweep path must be non-degenerate")));let mut v=sweep();v.profile.radius=0.;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("sweep profile radius must exceed modeling tolerance")));}
 #[test]fn sweep_rejects_non_finite_geometry(){let mut v=sweep();v.profile.radius=f64::NAN;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("sweep contains non-finite geometry")));}
 fn two()->TwoSegmentCircularSweep{TwoSegmentCircularSweep{profile:CircularProfile{center:Point3{x:0.,y:0.,z:0.},normal:Point3{x:1.,y:0.,z:0.},radius:1.},corner:Point3{x:10.,y:0.,z:0.},end:Point3{x:10.,y:10.,z:0.}}}
 #[test]fn two_segment_lengths_are_exact(){assert_eq!(two().segment_lengths(tolerance()).unwrap(),(10.,10.));assert_eq!(two().total_path_length(tolerance()).unwrap(),20.);}
 #[test]fn two_segment_rejects_collinear_path(){let mut v=two();v.end=Point3{x:20.,y:0.,z:0.};assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("two-segment sweep requires a genuine path corner")));}
 #[test]fn two_segment_rejects_degenerate_first_segment(){let mut v=two();v.corner=v.profile.center;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("two-segment sweep requires a non-degenerate first segment")));}
 #[test]fn two_segment_rejects_degenerate_second_segment(){let mut v=two();v.end=v.corner;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("two-segment sweep requires a non-degenerate second segment")));}
 #[test]fn two_segment_rejects_wrong_profile_normal(){let mut v=two();v.profile.normal=Point3{x:0.,y:1.,z:0.};assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("two-segment sweep profile normal must be parallel to first path segment")));}
 #[test]fn two_segment_rejects_non_finite_radius(){let mut v=two();v.profile.radius=f64::INFINITY;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("two-segment sweep contains non-finite geometry")));}
 fn variable()->LinearVariableRadiusSweep{LinearVariableRadiusSweep{start:Point3{x:0.,y:0.,z:0.},end:Point3{x:0.,y:0.,z:10.},normal:Point3{x:0.,y:0.,z:1.},start_radius:1.,end_radius:2.}}
 #[test]fn variable_radius_sweep_has_exact_length_and_frustum_volume(){let v=variable();assert_eq!(v.length(tolerance()).unwrap(),10.);assert!((v.volume(tolerance()).unwrap()-(70./3.)*std::f64::consts::PI).abs()<1e-12);}
 #[test]fn equal_variable_radii_reduce_to_cylinder_volume(){let mut v=variable();v.end_radius=v.start_radius;assert!((v.volume(tolerance()).unwrap()-10.*std::f64::consts::PI).abs()<1e-12);}
 #[test]fn variable_radius_sweep_accepts_antiparallel_normal(){let mut v=variable();v.normal=Point3{x:0.,y:0.,z:-1.};assert!(v.validate(tolerance()).is_ok());}
 #[test]fn variable_radius_sweep_rejects_invalid_inputs(){let mut v=variable();v.start_radius=0.;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("variable-radius sweep radii must exceed modeling tolerance")));let mut v=variable();v.end=v.start;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("variable-radius sweep path must be non-degenerate")));let mut v=variable();v.normal=Point3{x:1.,y:0.,z:0.};assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("variable-radius sweep normal must be parallel to the path")));let mut v=variable();v.end_radius=f64::NAN;assert_eq!(v.validate(tolerance()),Err(GeometryError::InvalidInput("variable-radius sweep contains non-finite geometry")));}
 #[test]fn variable_radius_sweep_alignment_is_finite(){let mut v=variable();v.end=Point3{x:3.,y:4.,z:12.};v.normal=Point3{x:3.,y:4.,z:12.};let(a,p)=v.alignment_to_z(tolerance()).unwrap();assert!(a.finite()&&p.is_finite());assert!((a.norm()-1.).abs()<1e-12);}
}