<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UMLCAD.Engineering.Cam</AssemblyName>
    <RootNamespace>UMLCAD.Engineering.Cam</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UMLCAD.Cad.Contracts/UMLCAD.Cad.Contracts.csproj" />
    <ProjectReference Include="../UMLCAD.Engineering.Resources/UMLCAD.Engineering.Resources.csproj" />
  </ItemGroup>
</Project>