<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/UMLCAD.Cad.Expressions/UMLCAD.Cad.Expressions.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Cad.Semantics/UMLCAD.Cad.Semantics.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Science/UMLCAD.Science.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Engineering.Resources/UMLCAD.Engineering.Resources.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Engineering.SheetMetal/UMLCAD.Engineering.SheetMetal.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Engineering.Cam/UMLCAD.Engineering.Cam.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Engineering.Drawing/UMLCAD.Engineering.Drawing.csproj" />
    <ProjectReference Include="../../src/UMLCAD.Integration.Simulation/UMLCAD.Integration.Simulation.csproj" />
  </ItemGroup>
</Project>
