<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UMLCAD.Cad.Semantics</AssemblyName>
    <RootNamespace>UMLCAD.Cad.Semantics</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UMLCAD.Cad.Contracts/UMLCAD.Cad.Contracts.csproj" />
    <ProjectReference Include="../UMLCAD.Cad.Expressions/UMLCAD.Cad.Expressions.csproj" />
  </ItemGroup>
</Project>