import { EPSILON, arcSpan, type ArcGeometry, type CircleGeometry, type Geometry, type LineGeometry, type Point2D } from "./core.js";
export interface SpatialResult { readonly firstGeometryId:string; readonly secondGeometryId:string; readonly distance:number; readonly intersects:boolean; readonly method:"exact-2d"; }
type Box={min:Point2D;max:Point2D};
const TWO_PI=2*Math.PI;
const sub=(a:Point2D,b:Point2D):Point2D=>({x:a.x-b.x,y:a.y-b.y});
const add=(a:Point2D,b:Point2D):Point2D=>({x:a.x+b.x,y:a.y+b.y});
const mul=(a:Point2D,s:number):Point2D=>({x:a.x*s,y:a.y*s});
const norm=(a:Point2D)=>Math.hypot(a.x,a.y);
const pd=(a:Point2D,b:Point2D)=>Math.hypot(a.x-b.x,a.y-b.y);
function box(g:Geometry):Box{if(g.kind==="line")return{min:{x:Math.min(g.start.x,g.end.x),y:Math.min(g.start.y,g.end.y)},max:{x:Math.max(g.start.x,g.end.x),y:Math.max(g.start.y,g.end.y)}};return{min:{x:g.center.x-g.radius,y:g.center.y-g.radius},max:{x:g.center.x+g.radius,y:g.center.y+g.radius}}}
function boxGap(a:Box,b:Box):number{return Math.hypot(Math.max(0,b.min.x-a.max.x,a.min.x-b.max.x),Math.max(0,b.min.y-a.max.y,a.min.y-b.max.y))}
function pointOnCircle(c:{readonly center:Point2D;readonly radius:number},angle:number):Point2D{return{x:c.center.x+c.radius*Math.cos(angle),y:c.center.y+c.radius*Math.sin(angle)}}
function arcContains(g:ArcGeometry,p:Point2D,tolerance=1e-10):boolean{const a=Math.atan2(p.y-g.center.y,p.x-g.center.x),span=arcSpan(g);for(let k=-2;k<=2;k+=1){const t=(a+TWO_PI*k-g.startAngle)/span;if(t>=-tolerance&&t<=1+tolerance)return true}return false}
function pointToSegment(p:Point2D,g:LineGeometry):number{const d=sub(g.end,g.start),l2=d.x*d.x+d.y*d.y,t=Math.max(0,Math.min(1,((p.x-g.start.x)*d.x+(p.y-g.start.y)*d.y)/l2));return pd(p,add(g.start,mul(d,t)))}
function pointToArc(p:Point2D,g:ArcGeometry):number{const v=sub(p,g.center),r=norm(v);if(r<=EPSILON)return Math.abs(g.radius);const radial={x:g.center.x+v.x*g.radius/r,y:g.center.y+v.y*g.radius/r};if(arcContains(g,radial))return pd(p,radial);return Math.min(pd(p,pointOnCircle(g,g.startAngle)),pd(p,pointOnCircle(g,g.endAngle)))}
function segmentIntersectsSegment(a:LineGeometry,b:LineGeometry,tolerance:number):boolean{const ax=a.end.x-a.start.x,ay=a.end.y-a.start.y,bx=b.end.x-b.start.x,by=b.end.y-b.start.y;const cross=(ux:number,uy:number,vx:number,vy:number)=>ux*vy-uy*vx;const den=cross(ax,ay,bx,by),cx=b.start.x-a.start.x,cy=b.start.y-a.start.y;if(Math.abs(den)>tolerance){const t=cross(cx,cy,bx,by)/den,u=cross(cx,cy,ax,ay)/den;return t>=-tolerance&&t<=1+tolerance&&u>=-tolerance&&u<=1+tolerance}return Math.abs(cross(cx,cy,ax,ay))<=tolerance&&Math.max(Math.min(a.start.x,a.end.x),Math.min(b.start.x,b.end.x))<=Math.min(Math.max(a.start.x,a.end.x),Math.max(b.start.x,b.end.x))+tolerance&&Math.max(Math.min(a.start.y,a.end.y),Math.min(b.start.y,b.end.y))<=Math.min(Math.max(a.start.y,a.end.y),Math.max(b.start.y,b.end.y))+tolerance}
function lineCircleIntersections(l:LineGeometry,c:{readonly center:Point2D;readonly radius:number}):Point2D[]{const dx=l.end.x-l.start.x,dy=l.end.y-l.start.y,fx=l.start.x-c.center.x,fy=l.start.y-c.center.y,a=dx*dx+dy*dy;if(a<=EPSILON)return[];const b=2*(fx*dx+fy*dy),cc=fx*fx+fy*fy-c.radius*c.radius,disc=b*b-4*a*cc;if(disc<-EPSILON)return[];const root=Math.sqrt(Math.max(0,disc)),out:Point2D[]=[];for(const t of[( -b-root)/(2*a),(-b+root)/(2*a)])if(t>=-1e-10&&t<=1+1e-10){const p={x:l.start.x+dx*t,y:l.start.y+dy*t};if(!out.some(q=>pd(p,q)<=1e-10))out.push(p)}return out}
function circleIntersections(a:{readonly center:Point2D;readonly radius:number},b:{readonly center:Point2D;readonly radius:number}):Point2D[]{const d=pd(a.center,b.center),sum=a.radius+b.radius,diff=Math.abs(a.radius-b.radius);if(d<=EPSILON)return[];if(d>sum+EPSILON||d<diff-EPSILON)return[];const x=(d*d-b.radius*b.radius+a.radius*a.radius)/(2*d),h2=a.radius*a.radius-x*x;if(h2<-EPSILON)return[];const h=Math.sqrt(Math.max(0,h2)),u={x:(b.center.x-a.center.x)/d,y:(b.center.y-a.center.y)/d},base=add(a.center,mul(u,x)),perp={x:-u.y,y:u.x};if(h<=EPSILON)return[base];return[add(base,mul(perp,h)),add(base,mul(perp,-h))]}
function distanceLineLine(a:LineGeometry,b:LineGeometry):number{if(segmentIntersectsSegment(a,b,EPSILON))return 0;return Math.min(pointToSegment(a.start,b),pointToSegment(a.end,b),pointToSegment(b.start,a),pointToSegment(b.end,a))}
function distanceLineCircle(l:LineGeometry,c:{readonly center:Point2D;readonly radius:number}):number{const dx=l.end.x-l.start.x,dy=l.end.y-l.start.y,d2=dx*dx+dy*dy;const t=((c.center.x-l.start.x)*dx+(c.center.y-l.start.y)*dy)/d2,tc=Math.max(0,Math.min(1,t)),foot={x:l.start.x+dx*tc,y:l.start.y+dy*tc},dmin=pd(c.center,foot),dmax=Math.max(pd(c.center,l.start),pd(c.center,l.end));if(dmin-EPSILON<=c.radius&&c.radius<=dmax+EPSILON)return 0;return Math.min(Math.abs(dmin-c.radius),Math.abs(dmax-c.radius))}
function distanceLineArc(l:LineGeometry,a:ArcGeometry):number{if(lineCircleIntersections(l,a).some(p=>arcContains(a,p)))return 0;const candidates=[pointToArc(l.start,a),pointToArc(l.end,a),pointToSegment(pointOnCircle(a,a.startAngle),l),pointToSegment(pointOnCircle(a,a.endAngle),l)];const dx=l.end.x-l.start.x,dy=l.end.y-l.start.y,len=Math.hypot(dx,dy);if(len>EPSILON){const nx=-dy/len,ny=dx/len;for(const s of[-1,1]){const p={x:a.center.x+nx*s*a.radius,y:a.center.y+ny*s*a.radius};const t=((p.x-l.start.x)*dx+(p.y-l.start.y)*dy)/(len*len);if(t>=-EPSILON&&t<=1+EPSILON&&arcContains(a,p))candidates.push(pointToSegment(p,l))}}return Math.min(...candidates)}
function distanceCircleCircle(a:CircleGeometry,b:CircleGeometry):number{const d=pd(a.center,b.center);if(d<=EPSILON&&Math.abs(a.radius-b.radius)<=EPSILON)return 0;if(Math.abs(a.radius-b.radius)-EPSILON<=d&&d<=a.radius+b.radius+EPSILON)return 0;return Math.max(0,Math.max(d-a.radius-b.radius,Math.abs(a.radius-b.radius)-d))}
function distanceCircleArc(c:CircleGeometry,a:ArcGeometry):number{if(Math.abs(c.radius-a.radius)<=EPSILON&&pd(c.center,a.center)<=EPSILON)return 0;if(circleIntersections(c,a).some(p=>arcContains(a,p)))return 0;const candidates=[Math.abs(pd(c.center,pointOnCircle(a,a.startAngle))-c.radius),Math.abs(pd(c.center,pointOnCircle(a,a.endAngle))-c.radius)];const delta=sub(a.center,c.center),d=norm(delta);if(d>EPSILON){const base=Math.atan2(delta.y,delta.x);for(const ang of[base,base+Math.PI]){const p=pointOnCircle(a,ang);if(arcContains(a,p))candidates.push(Math.abs(pd(c.center,p)-c.radius))}}return Math.min(...candidates)}
function distanceArcArc(a:ArcGeometry,b:ArcGeometry):number{if(pd(a.center,b.center)<=EPSILON&&Math.abs(a.radius-b.radius)<=EPSILON){for(const p of[pointOnCircle(a,a.startAngle),pointOnCircle(a,a.endAngle),pointOnCircle(b,b.startAngle),pointOnCircle(b,b.endAngle)])if(arcContains(a,p)&&arcContains(b,p))return 0;return Math.min(pointToArc(pointOnCircle(a,a.startAngle),b),pointToArc(pointOnCircle(a,a.endAngle),b),pointToArc(pointOnCircle(b,b.startAngle),a),pointToArc(pointOnCircle(b,b.endAngle),a))}const intersections=circleIntersections(a,b);if(intersections.some(p=>arcContains(a,p)&&arcContains(b,p)))return 0;const candidates=[pointToArc(pointOnCircle(a,a.startAngle),b),pointToArc(pointOnCircle(a,a.endAngle),b),pointToArc(pointOnCircle(b,b.startAngle),a),pointToArc(pointOnCircle(b,b.endAngle),a)];const delta=sub(b.center,a.center),d=norm(delta);if(d>EPSILON){const base=Math.atan2(delta.y,delta.x);for(const ang of[base,base+Math.PI]){const pa=pointOnCircle(a,ang);if(arcContains(a,pa))candidates.push(pointToArc(pa,b));const pb=pointOnCircle(b,ang);if(arcContains(b,pb))candidates.push(pointToArc(pb,a))}}return Math.min(...candidates)}
function exactDistance(a:Geometry,b:Geometry):number{if(a.kind==="line"&&b.kind==="line")return distanceLineLine(a,b);if(a.kind==="line"&&b.kind==="circle")return distanceLineCircle(a,b);if(a.kind==="circle"&&b.kind==="line")return distanceLineCircle(b,a);if(a.kind==="line"&&b.kind==="arc")return distanceLineArc(a,b);if(a.kind==="arc"&&b.kind==="line")return distanceLineArc(b,a);if(a.kind==="circle"&&b.kind==="circle")return distanceCircleCircle(a,b);if(a.kind==="circle"&&b.kind==="arc")return distanceCircleArc(a,b);if(a.kind==="arc"&&b.kind==="circle")return distanceCircleArc(b,a);return distanceArcArc(a as ArcGeometry,b as ArcGeometry)}
export function spatialAnalysis(items:readonly {readonly id:string;readonly geometry:Geometry}[],tolerance=1e-8):readonly SpatialResult[]{if(!Number.isFinite(tolerance)||tolerance<0)throw Error("Spatial tolerance must be finite and non-negative");const out:SpatialResult[]=[];for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=items[i]!,b=items[j]!,broadGap=boxGap(box(a.geometry),box(b.geometry));const distance=broadGap>tolerance?broadGap:exactDistance(a.geometry,b.geometry);out.push(Object.freeze({firstGeometryId:a.id,secondGeometryId:b.id,distance,intersects:distance<=tolerance,method:"exact-2d"}))}return Object.freeze(out)}
export function distancePoint(a:Point2D,b:Point2D):number{return pd(a,b)}
