<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>UMLCAD.Application</AssemblyName>
    <RootNamespace>UMLCAD.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../framework/libraries/UMLCAD.Framework/UMLCAD.Framework.csproj" />
  </ItemGroup>
</Project>
