use umlcad_v6_geometry_api::{GeometryBackend, GeometryError, GeometryResult, ToleranceContext};

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BoxAllEdgesFillet { pub width:f64,pub depth:f64,pub height:f64,pub radius:f64 }
impl BoxAllEdgesFillet {
 pub fn validate(self,tolerance:ToleranceContext)->Result<(),GeometryError>{tolerance.validate()?;if !self.width.is_finite()||!self.depth.is_finite()||!self.height.is_finite()||!self.radius.is_finite(){return Err(GeometryError::InvalidInput("box fillet dimensions and radius must be finite"));}if self.width<=tolerance.modeling||self.depth<=tolerance.modeling||self.height<=tolerance.modeling{return Err(GeometryError::InvalidInput("box fillet dimensions must exceed modeling tolerance"));}if self.radius<=tolerance.modeling{return Err(GeometryError::InvalidInput("box fillet radius must exceed modeling tolerance"));}if 2.0*self.radius>=self.width.min(self.depth).min(self.height){return Err(GeometryError::InvalidInput("box fillet radius must be strictly less than half the minimum box dimension"));}Ok(())}
 pub fn source_volume(self,tolerance:ToleranceContext)->Result<f64,GeometryError>{self.validate(tolerance)?;let v=self.width*self.depth*self.height;if !v.is_finite(){return Err(GeometryError::InvalidInput("box fillet source volume is not finite"));}Ok(v)}
 pub fn rounded_box_volume(self,tolerance:ToleranceContext)->Result<f64,GeometryError>{self.validate(tolerance)?;let a=self.width;let b=self.depth;let c=self.height;let r=self.radius;let v=a*b*c-2.0*r*(a*b+a*c+b*c)+std::f64::consts::PI*r*r*(a+b+c)+(4.0*std::f64::consts::PI/3.0-8.0)*r*r*r;if !v.is_finite()||v<=0.0{return Err(GeometryError::InvalidInput("box fillet analytic volume is not finite and positive"));}Ok(v)}
 pub fn realize_with<B:GeometryBackend>(self,backend:&B,tolerance:ToleranceContext)->Result<GeometryResult<B::Shape>,GeometryError>{self.validate(tolerance)?;let source=backend.box_solid(self.width,self.depth,self.height,tolerance)?.shape;backend.fillet_all_edges(&source,self.radius,tolerance)}
}
pub trait FilletBackend:GeometryBackend{fn fillet_box_all_edges(&self,definition:BoxAllEdgesFillet,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>;}
impl<B:GeometryBackend> FilletBackend for B{fn fillet_box_all_edges(&self,definition:BoxAllEdgesFillet,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{definition.realize_with(self,tolerance)}}
#[cfg(test)]mod tests{use super::*;fn tolerance()->ToleranceContext{ToleranceContext{modeling:1e-9,validation:1e-9}}fn definition()->BoxAllEdgesFillet{BoxAllEdgesFillet{width:20.,depth:30.,height:40.,radius:2.}}
#[test]fn validates_strict_radius_bound(){let mut d=definition();assert!(d.validate(tolerance()).is_ok());d.radius=10.;assert_eq!(d.validate(tolerance()),Err(GeometryError::InvalidInput("box fillet radius must be strictly less than half the minimum box dimension")));}
#[test]fn computes_exact_source_and_rounded_volume(){let d=definition();assert_eq!(d.source_volume(tolerance()).unwrap(),24000.);let expected=20.*30.*40.-2.*2.*(20.*30.+20.*40.+30.*40.)+std::f64::consts::PI*4.*90.+(4.*std::f64::consts::PI/3.-8.)*8.;assert!((d.rounded_box_volume(tolerance()).unwrap()-expected).abs()<1e-10);assert!(d.rounded_box_volume(tolerance()).unwrap()<d.source_volume(tolerance()).unwrap());}
#[test]fn rejects_nonfinite_and_nonpositive_geometry(){let mut d=definition();d.width=f64::NAN;assert!(d.validate(tolerance()).is_err());let mut d=definition();d.radius=f64::INFINITY;assert!(d.validate(tolerance()).is_err());let mut d=definition();d.depth=0.;assert!(d.validate(tolerance()).is_err());let mut d=definition();d.radius=0.;assert!(d.validate(tolerance()).is_err());}}
