use std::ptr::NonNull;
use umlcad_v6_geometry_api::{BoundingBox, EdgeDescriptor, FaceDescriptor, GeometryBackend, GeometryError, GeometryEvidence, GeometryKind, GeometryResult, GeometryStatus, ToleranceContext, TopologyCounts, ValidationResult, VertexDescriptor};
mod tessellation;
mod exchange;
mod nurbs_surface;
mod offsets;
#[repr(C)] struct NativeShape{_private:[u8;0]}
unsafe extern "C"{
 fn umlcad_occt_box(width:f64,depth:f64,height:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_cylinder(radius:f64,height:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_sphere(radius:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_cone(base_radius:f64,top_radius:f64,height:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_torus(major_radius:f64,minor_radius:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_circle_curve(radius:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_line_curve(x1:f64,y1:f64,z1:f64,x2:f64,y2:f64,z2:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_shape_curve_length(input:*const NativeShape,out_length:*mut f64)->i32;
 fn umlcad_occt_extrude_polygon(points_xy:*const f64,point_count:u32,height:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_revolve_polygon(profile_rz:*const f64,point_count:u32,angle_radians:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_loft_polygons(lower_xy:*const f64,lower_count:u32,lower_z:f64,upper_xy:*const f64,upper_count:u32,upper_z:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_fillet_all_edges(input:*const NativeShape,radius:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_chamfer_all_edges(input:*const NativeShape,distance:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_fuse(left:*const NativeShape,right:*const NativeShape,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_common(left:*const NativeShape,right:*const NativeShape,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_cut(left:*const NativeShape,right:*const NativeShape,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_shape_clone(input:*const NativeShape,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_shape_translate(input:*const NativeShape,dx:f64,dy:f64,dz:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_shape_rotate(input:*const NativeShape,axis_x:f64,axis_y:f64,axis_z:f64,angle_radians:f64,out_shape:*mut *mut NativeShape)->i32;
 fn umlcad_occt_shape_bounding_box(input:*const NativeShape,out_bounds:*mut f64)->i32;
 fn umlcad_occt_shape_topology_counts(input:*const NativeShape,out_counts:*mut u32)->i32;
 fn umlcad_occt_shape_face_descriptor_count(input:*const NativeShape,out_count:*mut u32)->i32;
 fn umlcad_occt_shape_face_descriptors(input:*const NativeShape,out_values:*mut f64,capacity:u32)->i32;
 fn umlcad_occt_shape_edge_descriptor_count(input:*const NativeShape,out_count:*mut u32)->i32;
 fn umlcad_occt_shape_edge_descriptors(input:*const NativeShape,out_values:*mut f64,capacity:u32)->i32;
 fn umlcad_occt_shape_vertex_descriptor_count(input:*const NativeShape,out_count:*mut u32)->i32;
 fn umlcad_occt_shape_vertex_descriptors(input:*const NativeShape,out_values:*mut f64,capacity:u32)->i32;
 fn umlcad_occt_shape_validate(input:*const NativeShape,valid:*mut i32,manifold:*mut i32)->i32;
 fn umlcad_occt_shape_delete(shape:*mut NativeShape);
}
const OCCT_OK:i32=0;const OCCT_INVALID_ARGUMENT:i32=1;const OCCT_NULL_SHAPE:i32=2;const OCCT_CONSTRUCTION_FAILED:i32=3;const OCCT_TRANSFORM_FAILED:i32=4;const OCCT_INTERNAL_ERROR:i32=5;const OCCT_REFERENCE_MIN_FEATURE:f64=1e-6;
pub struct OcctShape{raw:NonNull<NativeShape>,kind:GeometryKind}
impl OcctShape{fn from_raw(raw:NonNull<NativeShape>,kind:GeometryKind)->Self{Self{raw,kind}}}
impl Clone for OcctShape{fn clone(&self)->Self{let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_shape_clone(self.raw.as_ptr(),&mut o)};assert_eq!(s,OCCT_OK);Self::from_raw(NonNull::new(o).expect("OCCT clone returned null"),self.kind)}}
impl Drop for OcctShape{fn drop(&mut self){unsafe{umlcad_occt_shape_delete(self.raw.as_ptr())}}}
pub struct OcctBackend;
impl OcctBackend{
 pub const fn new()->Self{Self}
 fn positive(v:f64,t:f64,label:&'static str)->Result<(),GeometryError>{if !v.is_finite()||v<=0.{return Err(GeometryError::InvalidInput(label))}if v<=OCCT_REFERENCE_MIN_FEATURE.max(t){return Err(GeometryError::InvalidInput("geometry feature is below the reference backend resolution"))}Ok(())}
 fn box_dims(w:f64,d:f64,h:f64,t:f64)->Result<(),GeometryError>{Self::positive(w,t,"box dimensions must be finite and positive")?;Self::positive(d,t,"box dimensions must be finite and positive")?;Self::positive(h,t,"box dimensions must be finite and positive")}
 fn cylinder(r:f64,h:f64,t:f64)->Result<(),GeometryError>{Self::positive(r,t,"cylinder radius must be finite and positive")?;Self::positive(h,t,"cylinder height must be finite and positive")}
 fn sphere(r:f64,t:f64)->Result<(),GeometryError>{Self::positive(r,t,"sphere radius must be finite and positive")}
 fn cone(br:f64,tr:f64,h:f64,t:f64)->Result<(),GeometryError>{Self::positive(br,t,"cone base radius must be finite and positive")?;Self::positive(tr,t,"cone top radius must be finite and positive")?;Self::positive(h,t,"cone height must be finite and positive")}
 fn torus(major:f64,minor:f64,t:f64)->Result<(),GeometryError>{Self::positive(major,t,"torus major radius must be finite and positive")?;Self::positive(minor,t,"torus minor radius must be finite and positive")?;if major<=minor{return Err(GeometryError::InvalidInput("torus major radius must be greater than minor radius"))}Ok(())}
 fn circle(radius:f64,t:f64)->Result<(),GeometryError>{Self::positive(radius,t,"circle radius must be finite and positive")}
 fn line(x1:f64,y1:f64,z1:f64,x2:f64,y2:f64,z2:f64)->Result<(),GeometryError>{let values=[x1,y1,z1,x2,y2,z2];if values.iter().any(|v|!v.is_finite()){return Err(GeometryError::InvalidInput("line endpoints must be finite"))}if x1==x2&&y1==y2&&z1==z2{return Err(GeometryError::InvalidInput("line endpoints must be distinct"))}Ok(())}
 fn polygon_extrusion(points:&[(f64,f64)],height:f64,t:f64)->Result<(),GeometryError>{if points.len()<3{return Err(GeometryError::InvalidInput("polygon extrusion requires at least three points"))}if points.iter().any(|(x,y)|!x.is_finite()||!y.is_finite()){return Err(GeometryError::InvalidInput("polygon coordinates must be finite"))}Self::positive(height,t,"extrusion height must be finite and positive")}
 fn polygon_revolution(profile:&[(f64,f64)],angle:f64,t:f64)->Result<(),GeometryError>{if profile.len()<3{return Err(GeometryError::InvalidInput("revolution profile requires at least three points"))}if profile.iter().any(|(r,z)|!r.is_finite()||!z.is_finite()||*r<=0.){return Err(GeometryError::InvalidInput("revolution profile must remain strictly outside the axis"))}if !angle.is_finite()||angle.abs()<=t.max(1e-12)||angle.abs()>std::f64::consts::TAU+t.max(1e-12){return Err(GeometryError::InvalidInput("revolution angle must be finite, non-zero, and no greater than one full turn"))}Ok(())}
 fn polygon_loft(lower:&[(f64,f64)],lz:f64,upper:&[(f64,f64)],uz:f64)->Result<(),GeometryError>{if lower.len()<3||upper.len()<3{return Err(GeometryError::InvalidInput("loft sections require at least three points"))}if lower.len()!=upper.len(){return Err(GeometryError::InvalidInput("loft sections must have equal vertex counts"))}if !lz.is_finite()||!uz.is_finite()||lz==uz{return Err(GeometryError::InvalidInput("loft section planes must be finite and distinct"))}for section in [lower,upper]{if section.iter().any(|(x,y)|!x.is_finite()||!y.is_finite()){return Err(GeometryError::InvalidInput("loft coordinates must be finite"))}}Ok(())}
 fn fillet_radius(r:f64,t:f64)->Result<(),GeometryError>{Self::positive(r,t,"fillet radius must be finite and positive")}
 fn chamfer_distance(d:f64,t:f64)->Result<(),GeometryError>{Self::positive(d,t,"chamfer distance must be finite and positive")}
 fn finite_translation(x:f64,y:f64,z:f64)->Result<(),GeometryError>{if !x.is_finite()||!y.is_finite()||!z.is_finite(){Err(GeometryError::InvalidInput("translation must be finite"))}else{Ok(())}}
 fn rotation(ax:f64,ay:f64,az:f64,a:f64)->Result<(),GeometryError>{if !ax.is_finite()||!ay.is_finite()||!az.is_finite()||!a.is_finite(){return Err(GeometryError::InvalidInput("rotation must be finite"))}if ax==0.&&ay==0.&&az==0.{return Err(GeometryError::InvalidInput("rotation axis must be non-zero"))}Ok(())}
 fn status(s:i32,op:&'static str)->GeometryError{match s{OCCT_INVALID_ARGUMENT=>GeometryError::InvalidInput(op),OCCT_NULL_SHAPE=>GeometryError::InvalidInput("OCCT shape is null"),OCCT_CONSTRUCTION_FAILED=>GeometryError::Unsupported("OCCT construction failed"),OCCT_TRANSFORM_FAILED=>GeometryError::Unsupported("OCCT transform failed"),OCCT_INTERNAL_ERROR=>GeometryError::Unsupported("OCCT internal failure"),_=>GeometryError::Unsupported("unknown OCCT status")}}
 fn evidence(&self,s:GeometryStatus,t:ToleranceContext)->GeometryEvidence{GeometryEvidence{status:s,backend:self.backend_name(),tolerance:t,message:None}}
}
impl Default for OcctBackend{fn default()->Self{Self::new()}}
impl GeometryBackend for OcctBackend{
 type Shape=OcctShape;
 fn backend_name(&self)->&'static str{"occt"}
 fn box_solid(&self,w:f64,d:f64,h:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::box_dims(w,d,h,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_box(w,d,h,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT box construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn cylinder_solid(&self,r:f64,h:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::cylinder(r,h,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_cylinder(r,h,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT cylinder construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn sphere_solid(&self,r:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::sphere(r,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_sphere(r,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT sphere construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn cone_solid(&self,br:f64,tr:f64,h:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::cone(br,tr,h,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_cone(br,tr,h,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT cone construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn torus_solid(&self,major:f64,minor:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::torus(major,minor,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_torus(major,minor,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT torus construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn circle_curve(&self,r:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::circle(r,t.modeling)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_circle_curve(r,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT circle construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Curve),kind:GeometryKind::Curve,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn line_curve(&self,x1:f64,y1:f64,z1:f64,x2:f64,y2:f64,z2:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::line(x1,y1,z1,x2,y2,z2)?;let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_line_curve(x1,y1,z1,x2,y2,z2,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT line construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Curve),kind:GeometryKind::Curve,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn curve_length(&self,s:&Self::Shape,t:ToleranceContext)->Result<f64,GeometryError>{t.validate()?;if s.kind!=GeometryKind::Curve{return Err(GeometryError::Unsupported("curve length requires a curve shape"))}let mut length=0.0;let st=unsafe{umlcad_occt_shape_curve_length(s.raw.as_ptr(),&mut length)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT curve length measurement failed"))}if !length.is_finite()||length<=0.0{return Err(GeometryError::Unsupported("OCCT returned invalid curve length"))}Ok(length)}
 fn extrude_polygon(&self,p:&[(f64,f64)],h:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::polygon_extrusion(p,h,t.modeling)?;let mut f=Vec::with_capacity(p.len()*2);for&(x,y)in p{f.push(x);f.push(y)}let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_extrude_polygon(f.as_ptr(),p.len()as u32,h,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT polygon extrusion construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn revolve_polygon(&self,p:&[(f64,f64)],a:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::polygon_revolution(p,a,t.modeling)?;let mut f=Vec::with_capacity(p.len()*2);for&(r,z)in p{f.push(r);f.push(z)}let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_revolve_polygon(f.as_ptr(),p.len()as u32,a,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT polygon revolution construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn loft_between_polygons(&self,l:&[(f64,f64)],lz:f64,u:&[(f64,f64)],uz:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::polygon_loft(l,lz,u,uz)?;let mut lf=Vec::with_capacity(l.len()*2);let mut uf=Vec::with_capacity(u.len()*2);for&(x,y)in l{lf.push(x);lf.push(y)}for&(x,y)in u{uf.push(x);uf.push(y)}let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_loft_polygons(lf.as_ptr(),l.len()as u32,lz,uf.as_ptr(),u.len()as u32,uz,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT polygon loft construction failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn fillet_all_edges(&self,shape:&Self::Shape,radius:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::fillet_radius(radius,t.modeling)?;let source_bounds=self.bounding_box(shape,t)?;let min_extent=(source_bounds.max_x-source_bounds.min_x).min((source_bounds.max_y-source_bounds.min_y).min(source_bounds.max_z-source_bounds.min_z));if radius*2.0>=min_extent{return Err(GeometryError::InvalidInput("fillet radius must be less than half the minimum source extent"))}let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_fillet_all_edges(shape.raw.as_ptr(),radius,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT all-edge fillet failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn chamfer_all_edges(&self,shape:&Self::Shape,distance:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::chamfer_distance(distance,t.modeling)?;let source_bounds=self.bounding_box(shape,t)?;let min_extent=(source_bounds.max_x-source_bounds.min_x).min((source_bounds.max_y-source_bounds.min_y).min(source_bounds.max_z-source_bounds.min_z));if distance*2.0>=min_extent{return Err(GeometryError::InvalidInput("chamfer distance must be less than half the minimum source extent"))}let mut o=std::ptr::null_mut();let s=unsafe{umlcad_occt_chamfer_all_edges(shape.raw.as_ptr(),distance,&mut o)};if s!=OCCT_OK{return Err(Self::status(s,"OCCT all-edge chamfer failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn fuse(&self,l:&Self::Shape,r:&Self::Shape,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{self.boolean(l,r,t,umlcad_occt_fuse)}
 fn common(&self,l:&Self::Shape,r:&Self::Shape,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{self.boolean(l,r,t,umlcad_occt_common)}
 fn cut(&self,l:&Self::Shape,r:&Self::Shape,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{self.boolean(l,r,t,umlcad_occt_cut)}
 fn translate(&self,s:&Self::Shape,dx:f64,dy:f64,dz:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::finite_translation(dx,dy,dz)?;let mut o=std::ptr::null_mut();let st=unsafe{umlcad_occt_shape_translate(s.raw.as_ptr(),dx,dy,dz,&mut o)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT translation failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,s.kind),kind:s.kind,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn rotate(&self,s:&Self::Shape,ax:f64,ay:f64,az:f64,a:f64,t:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{t.validate()?;Self::rotation(ax,ay,az,a)?;let mut o=std::ptr::null_mut();let st=unsafe{umlcad_occt_shape_rotate(s.raw.as_ptr(),ax,ay,az,a,&mut o)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT rotation failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,s.kind),kind:s.kind,evidence:self.evidence(GeometryStatus::Success,t)})}
 fn bounding_box(&self,s:&Self::Shape,t:ToleranceContext)->Result<BoundingBox,GeometryError>{t.validate()?;let mut v=[0.;6];let st=unsafe{umlcad_occt_shape_bounding_box(s.raw.as_ptr(),v.as_mut_ptr())};if st!=OCCT_OK{return Err(Self::status(st,"OCCT bounding-box measurement failed"))}let b=BoundingBox{min_x:v[0],min_y:v[1],min_z:v[2],max_x:v[3],max_y:v[4],max_z:v[5]};b.validate()?;Ok(b)}
 fn topology_counts(&self,s:&Self::Shape,t:ToleranceContext)->Result<TopologyCounts,GeometryError>{t.validate()?;let mut v=[0;5];let st=unsafe{umlcad_occt_shape_topology_counts(s.raw.as_ptr(),v.as_mut_ptr())};if st!=OCCT_OK{return Err(Self::status(st,"OCCT topology-count measurement failed"))}Ok(TopologyCounts{solids:v[0],shells:v[1],faces:v[2],edges:v[3],vertices:v[4]})}
 fn face_descriptors(&self,s:&Self::Shape,t:ToleranceContext)->Result<Vec<FaceDescriptor>,GeometryError>{t.validate()?;let mut count=0u32;let st=unsafe{umlcad_occt_shape_face_descriptor_count(s.raw.as_ptr(),&mut count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT face descriptor count failed"))}if count==0{return Ok(Vec::new())}let mut values=vec![0.0f64;count as usize*8];let st=unsafe{umlcad_occt_shape_face_descriptors(s.raw.as_ptr(),values.as_mut_ptr(),count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT face descriptor extraction failed"))}let mut descriptors=Vec::with_capacity(count as usize);for chunk in values.chunks_exact(8){let edge_count=chunk[7] as u32;if (chunk[7]-edge_count as f64).abs()>0.0{return Err(GeometryError::InvalidInput("face descriptor edge count is not integral"))}let d=FaceDescriptor{area:chunk[0],bounds:BoundingBox{min_x:chunk[1],min_y:chunk[2],min_z:chunk[3],max_x:chunk[4],max_y:chunk[5],max_z:chunk[6]},boundary_edge_count:edge_count};d.validate()?;descriptors.push(d)}Ok(descriptors)}
 fn edge_descriptors(&self,s:&Self::Shape,t:ToleranceContext)->Result<Vec<EdgeDescriptor>,GeometryError>{t.validate()?;let mut count=0u32;let st=unsafe{umlcad_occt_shape_edge_descriptor_count(s.raw.as_ptr(),&mut count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT edge descriptor count failed"))}if count==0{return Ok(Vec::new())}let mut values=vec![0.0f64;count as usize*9];let st=unsafe{umlcad_occt_shape_edge_descriptors(s.raw.as_ptr(),values.as_mut_ptr(),count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT edge descriptor extraction failed"))}let mut descriptors=Vec::with_capacity(count as usize);for chunk in values.chunks_exact(9){let face_use=chunk[7] as u32;let vertex_use=chunk[8] as u32;if (chunk[7]-face_use as f64).abs()>0.0||(chunk[8]-vertex_use as f64).abs()>0.0{return Err(GeometryError::InvalidInput("edge descriptor incidence count is not integral"))}let d=EdgeDescriptor{length:chunk[0],bounds:BoundingBox{min_x:chunk[1],min_y:chunk[2],min_z:chunk[3],max_x:chunk[4],max_y:chunk[5],max_z:chunk[6]},face_use_count:face_use,vertex_use_count:vertex_use};d.validate()?;descriptors.push(d)}Ok(descriptors)}
 fn vertex_descriptors(&self,s:&Self::Shape,t:ToleranceContext)->Result<Vec<VertexDescriptor>,GeometryError>{t.validate()?;let mut count=0u32;let st=unsafe{umlcad_occt_shape_vertex_descriptor_count(s.raw.as_ptr(),&mut count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT vertex descriptor count failed"))}if count==0{return Ok(Vec::new())}let mut values=vec![0.0f64;count as usize*5];let st=unsafe{umlcad_occt_shape_vertex_descriptors(s.raw.as_ptr(),values.as_mut_ptr(),count)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT vertex descriptor extraction failed"))}let mut descriptors=Vec::with_capacity(count as usize);for chunk in values.chunks_exact(5){let edge_use=chunk[3] as u32;let face_use=chunk[4] as u32;if (chunk[3]-edge_use as f64).abs()>0.0||(chunk[4]-face_use as f64).abs()>0.0{return Err(GeometryError::InvalidInput("vertex descriptor incidence count is not integral"))}let d=VertexDescriptor{x:chunk[0],y:chunk[1],z:chunk[2],edge_use_count:edge_use,face_use_count:face_use};d.validate()?;descriptors.push(d)}Ok(descriptors)}
 fn validate(&self,s:&Self::Shape,t:ToleranceContext)->Result<ValidationResult,GeometryError>{t.validate()?;let(mut valid,mut manifold)=(0,0);let st=unsafe{umlcad_occt_shape_validate(s.raw.as_ptr(),&mut valid,&mut manifold)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT validation failed"))}let valid_bool=valid!=0;let mut manifold_bool=manifold!=0;if valid_bool&&!manifold_bool{let c=self.topology_counts(s,t)?;manifold_bool=c.solids==1&&c.shells==1&&c.faces>=1&&c.edges>=1&&c.vertices>=1}Ok(ValidationResult{valid:valid_bool,manifold:manifold_bool,message:None})}
}
impl OcctBackend{fn boolean(&self,l:&OcctShape,r:&OcctShape,t:ToleranceContext,op:unsafe extern "C" fn(*const NativeShape,*const NativeShape,*mut*mut NativeShape)->i32)->Result<GeometryResult<OcctShape>,GeometryError>{t.validate()?;let mut o=std::ptr::null_mut();let st=unsafe{op(l.raw.as_ptr(),r.raw.as_ptr(),&mut o)};if st!=OCCT_OK{return Err(Self::status(st,"OCCT Boolean operation failed"))}let raw=NonNull::new(o).ok_or(GeometryError::Unsupported("OCCT returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,t)})}}
#[cfg(test)]mod tests{use super::*;const T:ToleranceContext=ToleranceContext{modeling:1e-9,validation:1e-9};#[test]fn boolean_family_is_valid(){let b=OcctBackend::new();let a=b.box_solid(10.,10.,10.,T).unwrap().shape;let q=b.box_solid(10.,10.,10.,T).unwrap().shape;let c=b.translate(&q,5.,0.,0.,T).unwrap().shape;for s in[b.fuse(&a,&c,T).unwrap().shape,b.common(&a,&c,T).unwrap().shape,b.cut(&a,&c,T).unwrap().shape]{assert!(b.validate(&s,T).unwrap().valid)}}#[test]fn fuse_is_deterministic(){let b=OcctBackend::new();let a=b.box_solid(10.,10.,10.,T).unwrap().shape;let q=b.box_solid(10.,10.,10.,T).unwrap().shape;let c=b.translate(&q,5.,0.,0.,T).unwrap().shape;let x=b.fuse(&a,&c,T).unwrap().shape;let y=b.fuse(&a,&c,T).unwrap().shape;assert_eq!(b.bounding_box(&x,T).unwrap(),b.bounding_box(&y,T).unwrap());assert_eq!(b.topology_counts(&x,T).unwrap(),b.topology_counts(&y,T).unwrap())}}
