use std::ptr::NonNull;
use crate::{NativeShape,OcctBackend,OcctShape};
use umlcad_v6_geometry_api::{GeometryBackend,GeometryError,GeometryKind,GeometryResult,GeometryStatus,ToleranceContext};
use umlcad_v6_nurbs_surface_api::{NurbsSurface3DDefinition,NurbsSurfaceBackend,Point3 as NurbsPoint3};
use umlcad_v6_offset_api::{OffsetBackend,PlanarLineSegment3D,PlanarSurfacePatch3D};
use umlcad_v6_sweep_api::{LinearCircularSweep,SweepBackend,TwoSegmentCircularSweep,TwoSegmentSweepBackend,LinearVariableRadiusSweep,VariableSweepBackend};
unsafe extern "C"{fn umlcad_occt_sweep_linear_circular(start_x:f64,start_y:f64,start_z:f64,end_x:f64,end_y:f64,end_z:f64,radius:f64,normal_x:f64,normal_y:f64,normal_z:f64,out_shape:*mut *mut NativeShape)->i32;}
impl OffsetBackend for OcctBackend{
 fn offset_planar_line(&self,definition:PlanarLineSegment3D,distance:f64,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{let r=definition.offset(distance,tolerance)?;self.line_curve(r.start.x,r.start.y,r.start.z,r.end.x,r.end.y,r.end.z,tolerance)}
 fn offset_planar_surface(&self,definition:PlanarSurfacePatch3D,distance:f64,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{let r=definition.offset(distance,tolerance)?;let u=r.u_dir.scale(r.width);let v=r.v_dir.scale(r.height);let p00=r.origin;let p01=r.origin.add_point(v);let p10=r.origin.add_point(u);let p11=p10.add_point(v);let s=NurbsSurface3DDefinition::new((1,1),vec![NurbsPoint3{x:p00.x,y:p00.y,z:p00.z},NurbsPoint3{x:p01.x,y:p01.y,z:p01.z},NurbsPoint3{x:p10.x,y:p10.y,z:p10.z},NurbsPoint3{x:p11.x,y:p11.y,z:p11.z}],vec![1.0;4],(2,2),vec![0.0,0.0,1.0,1.0],vec![0.0,0.0,1.0,1.0]);self.nurbs_surface3d(&s,tolerance)} }
impl SweepBackend for OcctBackend{fn sweep_linear_circular(&self,definition:LinearCircularSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{definition.validate(tolerance)?;let mut raw=std::ptr::null_mut();let status=unsafe{umlcad_occt_sweep_linear_circular(definition.path.start.x,definition.path.start.y,definition.path.start.z,definition.path.end.x,definition.path.end.y,definition.path.end.z,definition.profile.radius,definition.profile.normal.x,definition.profile.normal.y,definition.profile.normal.z,&mut raw)};if status!=crate::OCCT_OK{return Err(Self::status(status,"OCCT linear circular sweep construction failed"));}let raw=NonNull::new(raw).ok_or(GeometryError::Unsupported("OCCT sweep returned null"))?;Ok(GeometryResult{shape:OcctShape::from_raw(raw,GeometryKind::Solid),kind:GeometryKind::Solid,evidence:self.evidence(GeometryStatus::Success,tolerance)})}}
impl TwoSegmentSweepBackend for OcctBackend{fn sweep_two_segment_circular(&self,definition:TwoSegmentCircularSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{definition.validate(tolerance)?;let first=LinearCircularSweep{profile:definition.profile,path:umlcad_v6_sweep_api::LinearPath{start:definition.profile.center,end:definition.corner}};let second=LinearCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:definition.corner,normal:umlcad_v6_sweep_api::Point3{x:definition.end.x-definition.corner.x,y:definition.end.y-definition.corner.y,z:definition.end.z-definition.corner.z},radius:definition.profile.radius},path:umlcad_v6_sweep_api::LinearPath{start:definition.corner,end:definition.end}};let a=first.realize_with(self,tolerance)?.shape;let b=second.realize_with(self,tolerance)?.shape;self.fuse(&a,&b,tolerance).map(|mut r|{r.kind=GeometryKind::Solid;r.evidence.status=GeometryStatus::Success;r})}}
impl VariableSweepBackend for OcctBackend{fn sweep_linear_variable_radius(&self,definition:LinearVariableRadiusSweep,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{definition.realize_with(self,tolerance)}}
#[cfg(test)]mod tests{use super::*;use umlcad_v6_geometry_api::GeometryBackend;const T:ToleranceContext=ToleranceContext{modeling:1e-9,validation:1e-9};const BT:f64=1e-6;
#[test]fn planar_line_offset_realizes_as_curve_without_mutating_source(){let b=OcctBackend::new();let s=PlanarLineSegment3D{start:umlcad_v6_offset_api::Point3{x:0.,y:0.,z:0.},end:umlcad_v6_offset_api::Point3{x:10.,y:0.,z:0.},plane_normal:umlcad_v6_offset_api::Point3{x:0.,y:0.,z:1.}};let r=b.offset_planar_line(s,2.,T).unwrap();assert_eq!(r.kind,GeometryKind::Curve);assert_eq!(b.curve_length(&r.shape,T).unwrap(),10.);assert_eq!(s.start,umlcad_v6_offset_api::Point3{x:0.,y:0.,z:0.});}
#[test]fn planar_surface_offset_realizes_as_one_surface_face(){let b=OcctBackend::new();let s=PlanarSurfacePatch3D{origin:umlcad_v6_offset_api::Point3{x:1.,y:2.,z:3.},u_dir:umlcad_v6_offset_api::Point3{x:1.,y:0.,z:0.},v_dir:umlcad_v6_offset_api::Point3{x:0.,y:1.,z:0.},width:5.,height:8.};let r=b.offset_planar_surface(s,4.,T).unwrap();let c=b.topology_counts(&r.shape,T).unwrap();let q=b.bounding_box(&r.shape,T).unwrap();assert_eq!(r.kind,GeometryKind::Surface);assert_eq!(c.faces,1);assert_eq!(c.solids,0);assert!((q.min_x-1.).abs()<=BT);assert!((q.max_x-6.).abs()<=BT);assert!((q.min_y-2.).abs()<=BT);assert!((q.max_y-10.).abs()<=BT);assert!((q.min_z-7.).abs()<=BT);assert!((q.max_z-7.).abs()<=BT);}
#[test]fn invalid_source_is_rejected_before_native_construction(){let b=OcctBackend::new();let s=PlanarLineSegment3D{start:umlcad_v6_offset_api::Point3{x:0.,y:0.,z:0.},end:umlcad_v6_offset_api::Point3{x:0.,y:0.,z:0.},plane_normal:umlcad_v6_offset_api::Point3{x:0.,y:0.,z:1.}};assert!(matches!(b.offset_planar_line(s,1.,T),Err(GeometryError::InvalidInput("planar line offset requires a non-degenerate segment"))));}
#[test]fn linear_circular_sweep_realizes_as_one_valid_solid(){let b=OcctBackend::new();let d=LinearCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:umlcad_v6_sweep_api::Point3{x:5.,y:-2.,z:3.},normal:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:1.},radius:2.},path:umlcad_v6_sweep_api::LinearPath{start:umlcad_v6_sweep_api::Point3{x:5.,y:-2.,z:3.},end:umlcad_v6_sweep_api::Point3{x:5.,y:-2.,z:13.}}};let r=b.sweep_linear_circular(d,T).unwrap();assert_eq!(r.kind,GeometryKind::Solid);let v=b.validate(&r.shape,T).unwrap();assert!(v.valid);assert!(v.manifold);let q=b.bounding_box(&r.shape,T).unwrap();assert!((q.min_x-3.).abs()<=1e-9);assert!((q.max_x-7.).abs()<=1e-9);assert!((q.min_y+4.).abs()<=1e-9);assert!((q.max_y-0.).abs()<=1e-9);assert!((q.min_z-3.).abs()<=1e-9);assert!((q.max_z-13.).abs()<=1e-9);assert!((std::f64::consts::PI*4.*10.-d.volume(T).unwrap()).abs()<=1e-12);}
#[test]fn linear_circular_sweep_supports_arbitrary_path_orientation(){let b=OcctBackend::new();let k=(89.0f64).sqrt();let d=LinearCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:umlcad_v6_sweep_api::Point3{x:1.,y:2.,z:3.},normal:umlcad_v6_sweep_api::Point3{x:5./k,y:0.,z:8./k},radius:1.},path:umlcad_v6_sweep_api::LinearPath{start:umlcad_v6_sweep_api::Point3{x:1.,y:2.,z:3.},end:umlcad_v6_sweep_api::Point3{x:6.,y:2.,z:11.}}};let r=b.sweep_linear_circular(d,T).unwrap();assert!(b.bounding_box(&r.shape,T).unwrap().min_x.is_finite());}
#[test]fn linear_circular_sweep_is_deterministic(){let b=OcctBackend::new();let d=LinearCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},normal:umlcad_v6_sweep_api::Point3{x:3./13.,y:4./13.,z:12./13.},radius:1.5},path:umlcad_v6_sweep_api::LinearPath{start:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},end:umlcad_v6_sweep_api::Point3{x:3.,y:4.,z:12.}}};let a=b.sweep_linear_circular(d,T).unwrap();let c=b.sweep_linear_circular(d,T).unwrap();assert_eq!(a.kind,c.kind);assert_eq!(b.topology_counts(&a.shape,T).unwrap(),b.topology_counts(&c.shape,T).unwrap());assert_eq!(b.bounding_box(&a.shape,T).unwrap(),b.bounding_box(&c.shape,T).unwrap());assert_eq!(a.evidence.status,GeometryStatus::Success);}
#[test]fn two_segment_sweep_realizes_as_valid_solid_with_expected_envelope(){let b=OcctBackend::new();let d=TwoSegmentCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},normal:umlcad_v6_sweep_api::Point3{x:1.,y:0.,z:0.},radius:1.},corner:umlcad_v6_sweep_api::Point3{x:10.,y:0.,z:0.},end:umlcad_v6_sweep_api::Point3{x:10.,y:10.,z:0.}};let r=b.sweep_two_segment_circular(d,T).unwrap();assert_eq!(r.kind,GeometryKind::Solid);assert!(b.validate(&r.shape,T).unwrap().valid);let q=b.bounding_box(&r.shape,T).unwrap();assert!(q.min_x<=0.&&q.max_x>=10.&&q.min_y<=0.&&q.max_y>=10.&&q.min_z<=0.&&q.max_z>=0.);}
#[test]fn two_segment_sweep_is_deterministic(){let b=OcctBackend::new();let d=TwoSegmentCircularSweep{profile:umlcad_v6_sweep_api::CircularProfile{center:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},normal:umlcad_v6_sweep_api::Point3{x:1.,y:0.,z:0.},radius:0.75},corner:umlcad_v6_sweep_api::Point3{x:4.,y:0.,z:0.},end:umlcad_v6_sweep_api::Point3{x:4.,y:3.,z:0.}};let a=b.sweep_two_segment_circular(d,T).unwrap();let c=b.sweep_two_segment_circular(d,T).unwrap();assert_eq!(b.topology_counts(&a.shape,T).unwrap(),b.topology_counts(&c.shape,T).unwrap());assert_eq!(b.bounding_box(&a.shape,T).unwrap(),b.bounding_box(&c.shape,T).unwrap());}
#[test]fn variable_radius_sweep_realizes_exact_frustum_geometry(){let b=OcctBackend::new();let d=LinearVariableRadiusSweep{start:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},end:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:10.},normal:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:1.},start_radius:1.,end_radius:2.};let r=b.sweep_linear_variable_radius(d,T).unwrap();assert_eq!(r.kind,GeometryKind::Solid);let v=b.validate(&r.shape,T).unwrap();assert!(v.valid);assert!(v.manifold);let q=b.bounding_box(&r.shape,T).unwrap();assert!((q.min_x+2.).abs()<=1e-9);assert!((q.max_x-2.).abs()<=1e-9);assert!((q.min_y+2.).abs()<=1e-9);assert!((q.max_y-2.).abs()<=1e-9);assert!((q.min_z-0.).abs()<=1e-9);assert!((q.max_z-10.).abs()<=1e-9);assert!((d.volume(T).unwrap()-(70./3.)*std::f64::consts::PI).abs()<=1e-12);}
#[test]fn variable_radius_sweep_equal_radii_is_cylinder_limit(){let b=OcctBackend::new();let d=LinearVariableRadiusSweep{start:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:0.},end:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:5.},normal:umlcad_v6_sweep_api::Point3{x:0.,y:0.,z:-1.},start_radius:2.,end_radius:2.};let r=b.sweep_linear_variable_radius(d,T).unwrap();assert_eq!(r.kind,GeometryKind::Solid);assert!(b.validate(&r.shape,T).unwrap().valid);assert!((d.volume(T).unwrap()-20.*std::f64::consts::PI).abs()<=1e-12);}
#[test]fn variable_radius_sweep_is_deterministic(){let b=OcctBackend::new();let d=LinearVariableRadiusSweep{start:umlcad_v6_sweep_api::Point3{x:1.,y:-2.,z:3.},end:umlcad_v6_sweep_api::Point3{x:6.,y:2.,z:15.},normal:umlcad_v6_sweep_api::Point3{x:5.,y:4.,z:12.},start_radius:0.75,end_radius:1.25};let a=b.sweep_linear_variable_radius(d,T).unwrap();let c=b.sweep_linear_variable_radius(d,T).unwrap();assert_eq!(b.topology_counts(&a.shape,T).unwrap(),b.topology_counts(&c.shape,T).unwrap());assert_eq!(b.bounding_box(&a.shape,T).unwrap(),b.bounding_box(&c.shape,T).unwrap());}
}