#[path = "curve_surface_operations.rs"]
mod curve_surface_operations;
#[path = "surface_surface_operations.rs"]
mod surface_surface_operations;
#[path = "point_surface_operations.rs"]
mod point_surface_operations;

use std::ptr::NonNull;
use super::super::{NativeShape, OcctBackend, OcctShape, OCCT_OK};
use umlcad_v6_geometry_api::{GeometryBackend, GeometryError, GeometryEvidence, GeometryKind, GeometryResult, GeometryStatus, ToleranceContext};
use umlcad_v6_nurbs_surface_api::{TrimmedNurbsSurface3DDefinition, TrimmedNurbsSurfaceBackend};
unsafe extern "C" { fn umlcad_occt_trimmed_nurbs_surface3d(poles_xyz:*const f64,count_u:u32,count_v:u32,weights:*const f64,knots_u:*const f64,knot_count_u:u32,knots_v:*const f64,knot_count_v:u32,degree_u:u32,degree_v:u32,loop_uv:*const f64,loop_counts:*const u32,loop_count:u32,face_tolerance:f64,out_shape:*mut *mut NativeShape)->i32; }
impl TrimmedNurbsSurfaceBackend for OcctBackend { fn trimmed_nurbs_surface3d(&self,definition:&TrimmedNurbsSurface3DDefinition,tolerance:ToleranceContext)->Result<GeometryResult<Self::Shape>,GeometryError>{tolerance.validate()?;definition.validate().map_err(|_|GeometryError::InvalidInput("invalid trimmed NURBS surface definition"))?;let mut poles_xyz=Vec::with_capacity(definition.surface.control_points.len()*3);for point in &definition.surface.control_points{poles_xyz.extend([point.x,point.y,point.z]);}let mut loop_uv=Vec::new();let mut loop_counts=Vec::with_capacity(definition.loops.len());for loop_ in &definition.loops{loop_counts.push(loop_.points.len() as u32);for point in &loop_.points{loop_uv.extend([point.u,point.v]);}}let mut raw=std::ptr::null_mut();let status=unsafe{umlcad_occt_trimmed_nurbs_surface3d(poles_xyz.as_ptr(),definition.surface.count_u as u32,definition.surface.count_v as u32,definition.surface.weights.as_ptr(),definition.surface.knots_u.as_ptr(),definition.surface.knots_u.len() as u32,definition.surface.knots_v.as_ptr(),definition.surface.knots_v.len() as u32,definition.surface.degree_u as u32,definition.surface.degree_v as u32,loop_uv.as_ptr(),loop_counts.as_ptr(),loop_counts.len() as u32,tolerance.modeling,&mut raw)};if status!=OCCT_OK{return Err(Self::status(status,"OCCT trimmed NURBS face construction failed"));}let raw=NonNull::new(raw).ok_or(GeometryError::Unsupported("OCCT returned null"))?;let shape=OcctShape::from_raw(raw,GeometryKind::Surface);let validation=self.validate(&shape,tolerance)?;if !validation.valid{return Err(GeometryError::Unsupported("OCCT produced an invalid trimmed face"));}Ok(GeometryResult{shape,kind:GeometryKind::Surface,evidence:GeometryEvidence{status:GeometryStatus::Success,backend:self.backend_name(),tolerance,message:None}})}}
#[cfg(test)]mod tests{use super::*;use umlcad_v6_geometry_api::GeometryBackend;use umlcad_v6_nurbs_surface_api::{NurbsSurface3DDefinition,ParameterPoint2,Point3,TrimLoop2D};const TOLERANCE:ToleranceContext=ToleranceContext{modeling:1e-9,validation:1e-9};fn plane()->NurbsSurface3DDefinition{NurbsSurface3DDefinition::new((1,1),vec![Point3{x:0.,y:0.,z:0.},Point3{x:0.,y:1.,z:0.},Point3{x:1.,y:0.,z:0.},Point3{x:1.,y:1.,z:0.}],vec![1.;4],(2,2),vec![0.,0.,1.,1.],vec![0.,0.,1.,1.])}fn outer()->TrimLoop2D{TrimLoop2D::new(vec![ParameterPoint2{u:0.1,v:0.1},ParameterPoint2{u:0.9,v:0.1},ParameterPoint2{u:0.9,v:0.9},ParameterPoint2{u:0.1,v:0.9}])}#[test]fn trimmed_face_is_valid_and_has_one_face(){let backend=OcctBackend::new();let result=backend.trimmed_nurbs_surface3d(&TrimmedNurbsSurface3DDefinition::new(plane(),vec![outer()]),TOLERANCE).unwrap();assert_eq!(result.kind,GeometryKind::Surface);assert_eq!(backend.topology_counts(&result.shape,TOLERANCE).unwrap().faces,1);let validation=backend.validate(&result.shape,TOLERANCE).unwrap();assert!(validation.valid);assert!(!validation.manifold)}#[test]fn hole_preserves_face_topology_and_reduces_planar_area(){let backend=OcctBackend::new();let hole=TrimLoop2D::new(vec![ParameterPoint2{u:0.3,v:0.3},ParameterPoint2{u:0.3,v:0.7},ParameterPoint2{u:0.7,v:0.7},ParameterPoint2{u:0.7,v:0.3}]);let full=backend.trimmed_nurbs_surface3d(&TrimmedNurbsSurface3DDefinition::new(plane(),vec![outer()]),TOLERANCE).unwrap();let trimmed=backend.trimmed_nurbs_surface3d(&TrimmedNurbsSurface3DDefinition::new(plane(),vec![outer(),hole]),TOLERANCE).unwrap();let full_area=backend.face_descriptors(&full.shape,TOLERANCE).unwrap()[0].area;let trimmed_area=backend.face_descriptors(&trimmed.shape,TOLERANCE).unwrap()[0].area;assert_eq!(backend.topology_counts(&trimmed.shape,TOLERANCE).unwrap().faces,1);assert!(trimmed_area<full_area);assert!(trimmed_area>0.0);assert!(!backend.validate(&trimmed.shape,TOLERANCE).unwrap().manifold)}#[test]fn invalid_trim_definition_fails_before_native_construction(){let backend=OcctBackend::new();let bad=TrimLoop2D::new(vec![ParameterPoint2{u:0.,v:0.},ParameterPoint2{u:1.,v:1.},ParameterPoint2{u:0.,v:1.},ParameterPoint2{u:1.,v:0.}]);assert!(matches!(backend.trimmed_nurbs_surface3d(&TrimmedNurbsSurface3DDefinition::new(plane(),vec![bad]),TOLERANCE),Err(GeometryError::InvalidInput("invalid trimmed NURBS surface definition"))))}}