#include <GeomAPI_IntCS.hxx>
#include <GeomAPI_IntSS.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Line.hxx>
#include <TColStd_Array1OfInteger.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_Array2OfReal.hxx>
#include <TColgp_Array1OfPnt.hxx>
#include <TColgp_Array2OfPnt.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Dir.hxx>
#include <gp_Lin.hxx>
#include <gp_Pnt.hxx>
#include <gp_Vec.hxx>
#include <cmath>
#include <cstdint>
#include <vector>
struct umlcad_occt_shape { TopoDS_Shape value; };
namespace {
struct KnotData { std::vector<double> values; std::vector<int> multiplicities; };
KnotData distinctKnots(const double* knots,uint32_t count){KnotData out;for(uint32_t i=0;i<count;++i){if(i==0||knots[i]!=knots[i-1]){out.values.push_back(knots[i]);out.multiplicities.push_back(1);}else{++out.multiplicities.back();}}return out;}
Handle(Geom_BSplineSurface) buildSurface(const double* poles_xyz,uint32_t count_u,uint32_t count_v,const double* weights,const double* knots_u,uint32_t knot_count_u,const double* knots_v,uint32_t knot_count_v,uint32_t degree_u,uint32_t degree_v){TColgp_Array2OfPnt poles(1,static_cast<Standard_Integer>(count_u),1,static_cast<Standard_Integer>(count_v));TColStd_Array2OfReal ws(1,static_cast<Standard_Integer>(count_u),1,static_cast<Standard_Integer>(count_v));for(uint32_t u=0;u<count_u;++u)for(uint32_t v=0;v<count_v;++v){const uint64_t i=static_cast<uint64_t>(u)*count_v+v;poles.SetValue(static_cast<Standard_Integer>(u+1),static_cast<Standard_Integer>(v+1),gp_Pnt(poles_xyz[3*i],poles_xyz[3*i+1],poles_xyz[3*i+2]));ws.SetValue(static_cast<Standard_Integer>(u+1),static_cast<Standard_Integer>(v+1),weights[i]);}const KnotData U=distinctKnots(knots_u,knot_count_u),V=distinctKnots(knots_v,knot_count_v);TColStd_Array1OfReal uk(1,static_cast<Standard_Integer>(U.values.size()));TColStd_Array1OfInteger um(1,static_cast<Standard_Integer>(U.values.size()));TColStd_Array1OfReal vk(1,static_cast<Standard_Integer>(V.values.size()));TColStd_Array1OfInteger vm(1,static_cast<Standard_Integer>(V.values.size()));for(std::size_t i=0;i<U.values.size();++i){uk.SetValue(static_cast<Standard_Integer>(i+1),U.values[i]);um.SetValue(static_cast<Standard_Integer>(i+1),U.multiplicities[i]);}for(std::size_t i=0;i<V.values.size();++i){vk.SetValue(static_cast<Standard_Integer>(i+1),V.values[i]);vm.SetValue(static_cast<Standard_Integer>(i+1),V.multiplicities[i]);}return new Geom_BSplineSurface(poles,ws,uk,vk,um,vm,static_cast<Standard_Integer>(degree_u),static_cast<Standard_Integer>(degree_v),Standard_False,Standard_False);}
Handle(Geom_BSplineCurve) buildCurve(const double* poles_xyz,uint32_t count,const double* weights,const double* knots,uint32_t knot_count,uint32_t degree){TColgp_Array1OfPnt poles(1,static_cast<Standard_Integer>(count));TColStd_Array1OfReal ws(1,static_cast<Standard_Integer>(count));for(uint32_t i=0;i<count;++i)poles.SetValue(static_cast<Standard_Integer>(i+1),gp_Pnt(poles_xyz[3*i],poles_xyz[3*i+1],poles_xyz[3*i+2])),ws.SetValue(static_cast<Standard_Integer>(i+1),weights[i]);const KnotData K=distinctKnots(knots,knot_count);TColStd_Array1OfReal kk(1,static_cast<Standard_Integer>(K.values.size()));TColStd_Array1OfInteger mm(1,static_cast<Standard_Integer>(K.values.size()));for(std::size_t i=0;i<K.values.size();++i){kk.SetValue(static_cast<Standard_Integer>(i+1),K.values[i]);mm.SetValue(static_cast<Standard_Integer>(i+1),K.multiplicities[i]);}return new Geom_BSplineCurve(poles,ws,kk,mm,static_cast<Standard_Integer>(degree),Standard_False,Standard_True);}
bool validSurface(const double* p,uint32_t cu,uint32_t cv,const double* w,const double* ku,uint32_t nu,const double* kv,uint32_t nv,uint32_t du,uint32_t dv){if(!p||!w||!ku||!kv||du==0||dv==0||cu<du+1||cv<dv+1||nu!=cu+du+1||nv!=cv+dv+1)return false;const uint64_t n=static_cast<uint64_t>(cu)*cv;for(uint64_t i=0;i<3*n;++i)if(!std::isfinite(p[i]))return false;for(uint64_t i=0;i<n;++i)if(!std::isfinite(w[i])||w[i]<=0)return false;for(uint32_t i=0;i<nu;++i)if(!std::isfinite(ku[i])||(i&&ku[i]<ku[i-1]))return false;for(uint32_t i=0;i<nv;++i)if(!std::isfinite(kv[i])||(i&&kv[i]<kv[i-1]))return false;return ku[cu]>ku[du]&&kv[cv]>kv[dv];}
bool validCurve(const double* p,uint32_t count,const double* w,const double* k,uint32_t knot_count,uint32_t degree){if(!p||!w||!k||degree==0||count<degree+1||knot_count!=count+degree+1)return false;for(uint64_t i=0;i<3*static_cast<uint64_t>(count);++i)if(!std::isfinite(p[i]))return false;for(uint32_t i=0;i<count;++i)if(!std::isfinite(w[i])||w[i]<=0)return false;for(uint32_t i=0;i<knot_count;++i)if(!std::isfinite(k[i])||(i&&k[i]<k[i-1]))return false;return k[count]>k[degree];}
bool validLine(const double* s,const double* e,double tol){if(!s||!e||!std::isfinite(tol)||tol<0)return false;for(int i=0;i<3;++i)if(!std::isfinite(s[i])||!std::isfinite(e[i]))return false;return (s[0]!=e[0]||s[1]!=e[1]||s[2]!=e[2]);}
bool validPoint(const double* p,double tol){if(!p||!std::isfinite(tol)||tol<0)return false;return std::isfinite(p[0])&&std::isfinite(p[1])&&std::isfinite(p[2]);}
}
extern "C" int32_t umlcad_occt_line_surface_intersection(const double* poles_xyz,uint32_t count_u,uint32_t count_v,const double* weights,const double* knots_u,uint32_t knot_count_u,const double* knots_v,uint32_t knot_count_v,uint32_t degree_u,uint32_t degree_v,const double* start_xyz,const double* end_xyz,double tolerance,double* out_values,uint32_t capacity,uint32_t* out_count,int32_t* out_tangent){if(!out_values||!out_count||!out_tangent)return 1;*out_count=0;*out_tangent=0;if(!validSurface(poles_xyz,count_u,count_v,weights,knots_u,knot_count_u,knots_v,knot_count_v,degree_u,degree_v)||!validLine(start_xyz,end_xyz,tolerance))return 1;try{const Handle(Geom_BSplineSurface) surface=buildSurface(poles_xyz,count_u,count_v,weights,knots_u,knot_count_u,knots_v,knot_count_v,degree_u,degree_v);if(surface.IsNull())return 3;gp_Vec delta(gp_Pnt(start_xyz[0],start_xyz[1],start_xyz[2]),gp_Pnt(end_xyz[0],end_xyz[1],end_xyz[2]));const gp_Pnt origin(start_xyz[0],start_xyz[1],start_xyz[2]);const gp_Dir direction(delta);const Handle(Geom_Line) line=new Geom_Line(gp_Lin(origin,direction));GeomAPI_IntCS inter(line,surface);if(!inter.IsDone())return 4;if(inter.NbSegments()>0){*out_tangent=1;return 0;}const double dx=delta.X(),dy=delta.Y(),dz=delta.Z(),den=dx*dx+dy*dy+dz*dz;uint32_t written=0;for(int i=1;i<=inter.NbPoints();++i){if(written>=capacity)return 1;double u=0,v=0,w=0;inter.Parameters(i,u,v,w);const gp_Pnt& p=inter.Point(i);const double t=((p.X()-start_xyz[0])*dx+(p.Y()-start_xyz[1])*dy+(p.Z()-start_xyz[2])*dz)/den;if(t<-tolerance||t>1.0+tolerance)continue;const uint32_t o=6*written;out_values[o]=u;out_values[o+1]=v;out_values[o+2]=t;out_values[o+3]=p.X();out_values[o+4]=p.Y();out_values[o+5]=p.Z();++written;}*out_count=written;return 0;}catch(...){return 5;}}
extern "C" int32_t umlcad_occt_nurbs_curve_surface_intersection(const double* curve_poles_xyz,uint32_t curve_count,const double* curve_weights,const double* curve_knots,uint32_t curve_knot_count,uint32_t curve_degree,const double* surface_poles_xyz,uint32_t count_u,uint32_t count_v,const double* surface_weights,const double* surface_knots_u,uint32_t surface_knot_count_u,const double* surface_knots_v,uint32_t surface_knot_count_v,uint32_t surface_degree_u,uint32_t surface_degree_v,double tolerance,double* out_values,uint32_t capacity,uint32_t* out_count,int32_t* out_tangent){if(!out_values||!out_count||!out_tangent)return 1;*out_count=0;*out_tangent=0;if(!std::isfinite(tolerance)||tolerance<0||!validCurve(curve_poles_xyz,curve_count,curve_weights,curve_knots,curve_knot_count,curve_degree)||!validSurface(surface_poles_xyz,count_u,count_v,surface_weights,surface_knots_u,surface_knot_count_u,surface_knots_v,surface_knot_count_v,surface_degree_u,surface_degree_v))return 1;try{const Handle(Geom_BSplineCurve) curve=buildCurve(curve_poles_xyz,curve_count,curve_weights,curve_knots,curve_knot_count,curve_degree);const Handle(Geom_BSplineSurface) surface=buildSurface(surface_poles_xyz,count_u,count_v,surface_weights,surface_knots_u,surface_knot_count_u,surface_knots_v,surface_knot_count_v,surface_degree_u,surface_degree_v);if(curve.IsNull()||surface.IsNull())return 3;GeomAPI_IntCS inter(curve,surface);if(!inter.IsDone())return 4;if(inter.NbSegments()>0){*out_tangent=1;return 0;}uint32_t written=0;const double first=curve->FirstParameter(),last=curve->LastParameter();for(int i=1;i<=inter.NbPoints();++i){if(written>=capacity)return 1;double u=0,v=0,t=0;inter.Parameters(i,u,v,t);if(t<first-tolerance||t>last+tolerance)continue;const gp_Pnt& p=inter.Point(i);const uint32_t o=6*written;out_values[o]=t;out_values[o+1]=u;out_values[o+2]=v;out_values[o+3]=p.X();out_values[o+4]=p.Y();out_values[o+5]=p.Z();++written;}*out_count=written;return 0;}catch(...){return 5;}}
extern "C" int32_t umlcad_occt_planar_surface_intersection(const double* poles_a,uint32_t count_ua,uint32_t count_va,const double* weights_a,const double* knots_ua,uint32_t knot_count_ua,const double* knots_va,uint32_t knot_count_va,uint32_t degree_ua,uint32_t degree_va,const double* poles_b,uint32_t count_ub,uint32_t count_vb,const double* weights_b,const double* knots_ub,uint32_t knot_count_ub,const double* knots_vb,uint32_t knot_count_vb,uint32_t degree_ub,uint32_t degree_vb,double tolerance,uint32_t* out_line_count,double* out_endpoints){if(!out_line_count||!out_endpoints)return 1;*out_line_count=0;for(int i=0;i<6;++i)out_endpoints[i]=0.0;if(!std::isfinite(tolerance)||tolerance<0||!validSurface(poles_a,count_ua,count_va,weights_a,knots_ua,knot_count_ua,knots_va,knot_count_va,degree_ua,degree_va)||!validSurface(poles_b,count_ub,count_vb,weights_b,knots_ub,knot_count_ub,knots_vb,knot_count_vb,degree_ub,degree_vb))return 1;try{const Handle(Geom_BSplineSurface) first=buildSurface(poles_a,count_ua,count_va,weights_a,knots_ua,knot_count_ua,knots_va,knot_count_va,degree_ua,degree_va);const Handle(Geom_BSplineSurface) second=buildSurface(poles_b,count_ub,count_vb,weights_b,knots_ub,knot_count_ub,knots_vb,knot_count_vb,degree_ub,degree_vb);if(first.IsNull()||second.IsNull())return 3;GeomAPI_IntSS inter(first,second,tolerance);if(!inter.IsDone())return 4;*out_line_count=static_cast<uint32_t>(inter.NbLines());if(*out_line_count>0){const Handle(Geom_Curve)& curve=inter.Line(1);if(curve.IsNull())return 5;const double first_parameter=curve->FirstParameter();const double last_parameter=curve->LastParameter();if(!std::isfinite(first_parameter)||!std::isfinite(last_parameter))return 5;gp_Pnt p0,p1;curve->D0(first_parameter,p0);curve->D0(last_parameter,p1);out_endpoints[0]=p0.X();out_endpoints[1]=p0.Y();out_endpoints[2]=p0.Z();out_endpoints[3]=p1.X();out_endpoints[4]=p1.Y();out_endpoints[5]=p1.Z();}return 0;}catch(...){return 5;}}
extern "C" int32_t umlcad_occt_point_surface_closest_point(const double* poles_xyz,uint32_t count_u,uint32_t count_v,const double* weights,const double* knots_u,uint32_t knot_count_u,const double* knots_v,uint32_t knot_count_v,uint32_t degree_u,uint32_t degree_v,const double* point_xyz,double tolerance,double* out_uv,double* out_point_xyz,double* out_distance){if(!out_uv||!out_point_xyz||!out_distance)return 1;*out_distance=0;if(!validPoint(point_xyz,tolerance)||!validSurface(poles_xyz,count_u,count_v,weights,knots_u,knot_count_u,knots_v,knot_count_v,degree_u,degree_v))return 1;try{const Handle(Geom_BSplineSurface) surface=buildSurface(poles_xyz,count_u,count_v,weights,knots_u,knot_count_u,knots_v,knot_count_v,degree_u,degree_v);if(surface.IsNull())return 3;const GeomAPI_ProjectPointOnSurf projection(gp_Pnt(point_xyz[0],point_xyz[1],point_xyz[2]),surface,tolerance);if(projection.NbPoints()<=0)return 4;double u=0,v=0;projection.LowerDistanceParameters(u,v);const gp_Pnt projected=projection.NearestPoint();out_uv[0]=u;out_uv[1]=v;out_point_xyz[0]=projected.X();out_point_xyz[1]=projected.Y();out_point_xyz[2]=projected.Z();*out_distance=projection.LowerDistance();return std::isfinite(u)&&std::isfinite(v)&&std::isfinite(out_point_xyz[0])&&std::isfinite(out_point_xyz[1])&&std::isfinite(out_point_xyz[2])&&std::isfinite(*out_distance)?0:5;}catch(...){return 5;}}