<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>UMLCAD.BenchVise</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../../framework/libraries/UMLCAD.Framework/UMLCAD.Framework.csproj" /><ProjectReference Include="../../../framework/libraries/UMLCAD.Cad.Expressions/UMLCAD.Cad.Expressions.csproj" /><ProjectReference Include="../../../framework/libraries/UMLCAD.Cad.Semantics/UMLCAD.Cad.Semantics.csproj" /></ItemGroup></Project>