<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>UMLCAD.SystemCad</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../UMLCAD.Framework/UMLCAD.Framework.csproj" />
    <ProjectReference Include="../UMLCAD.Kernel.Client/UMLCAD.Kernel.Client.csproj" />
  </ItemGroup>
</Project>
